---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

components:
  - ../../components/sops

resources:
  - ./namespace.yaml
  - ./cilium/ks.yaml
  - ./coredns/ks.yaml
  - ./intel-gpu-plugin/ks.yaml
  - ./intel-gpu-resource-driver/ks.yaml
  - ./metrics-server/ks.yaml
  - ./node-feature-discovery/ks.yaml
  - ./node-feature-discovery/rules-ks.yaml
  - ./reloader/ks.yaml
  - ./spegel/ks.yaml
