---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./ocirepository.yaml
  - ./helmrelease.yaml
  - ./secrets.sops.yaml
configMapGenerator:
  - name: garage-config
    files:
      - ./resources/garage.toml
generatorOptions:
  disableNameSuffixHash: true
