apiVersion: v1
kind: Secret
metadata:
  name: garage-secrets
stringData:
  GARAGE_RPC_SECRET: ENC[AES256_GCM,data:uIxETWg35bWoXnFsv+9zWI/h4UcEsy6Q8zl34ERkAZAxxwWWhx/r582NYMm79xZoZzPkXVTrmSQ55xHvgr7ztA==,iv:v1XFOF2y0dTl2CPZIyxalGCnRUVtPCpH4nY1XDT99pY=,tag:Kw14vwhVrPPUSJnN9q0zRg==,type:str]
  GARAGE_ADMIN_TOKEN: ENC[AES256_GCM,data:Cyr4GxMtLcEedSoIri6rohWFw0IprTRql9ashUIP2NBuBDHsMxVYc4VzQLQ8e76ZzX/JewCcsc+cKc8hWwRwmQ==,iv:lI/Ew3wBU+3kZmULBGfBwAx5i1Mb95neZyOIpURv+/8=,tag:jjvBBcmWvXfqYJK5ga7vCw==,type:str]
sops:
  age:
    - recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBndEFpZlpqTVVqSXI3V09y
        TThERHVhR3EwMjVtTGN3YWQvUmhVeW0yQmd3CjBFektySi81U3BaSWM1Nms4VTlY
        d3FvNi9pT2R4VVY0K3FlVDZtSW5helkKLS0tIEk4QjFDVEF4SnlLN0FFMU9YK1ZE
        K3dsZmxIQjB6Mi9WOGtjd25lVlQ0TWMKL0eW7V2yz0zBulGQtmFtmF1ES5Vikgg3
        T477D+xPrQzWhR5d9eV2B9x2GAg8zjhyakMwAKuj203uVJFDvLQCgw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-20T23:17:41Z"
  mac: ENC[AES256_GCM,data:0fqOL4KaNmA+OhDqOFC8eyCyWoVMlpq3IE1Z+icFssUNFow1U5hsS2QG1oI0CXLKBsXL76IJK6p882QSn41QhGFJ6jDQNPblv/x3nPpq7/WPbAjRHEvkFsAyM+FQUSRDWNqGKI/PXWukHqQH+3mtOng39K2bGTgBIlBB9ZBsCQA=,iv:C5Uxn8+rKFeoqphwBcTIZMymCEvJNsvKwCD2jDoNOBs=,tag:BbGZvZIFphHPfE8os2qc3A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
