apiVersion: v1
kind: Secret
metadata:
  name: credentials-authentik
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:LrIP5M7Gkp0+,iv:kKfmrxZmpbdzac+bMLexlz0q+8FGrVXxh4tlKIg3IfE=,tag:TEkmopDCRpYgYP98d+j3QQ==,type:str]
  password: ENC[AES256_GCM,data:J8K56bi50nQwgZhNJxQeGvUsLnrM8EM0LdfMeGqRQIc4uSSbNq0VXFrlhN2XU4GR,iv:OY7w/+bV8ndvrc0Mie0y65/4A15qxAZ61+OS1DaaKB4=,tag:RucZHn326EH2bvrOksB2CA==,type:str]
sops:
  age:
    - recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWdENrUTM5VjFHN0xiaENG
        NVE5WmNaazllVXlJUnZleVc3LzdObGdlWkdVClgvTUFJVW11YnNzNHhWc3hLdktC
        dzZqZkRPdDZWZEpnOUFIZG9iYllycEEKLS0tIHZFYytaZkpGTWhWallwTDBVbSti
        aG02MFR5aHJYZkdmR2Z4OGRURmNSR2sKlM8cM236dm2lpbrV7+ClRnMRrqhMnZQC
        qIF3hzFFBSoddfC/vUxwjYzbXwKyq/j/ZDB6iIHNkXk3SpLretWW+w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-02T21:01:22Z"
  mac: ENC[AES256_GCM,data:qd8T/2i0HXROCBhqmAx/y34mg4UXrtG0uAQzAl8QisO/9vsmq2yxuQKhoJG+Ke7sS1HidZvRx9u/Vkam6wbMp6nipuHOGhKyPsd6ZdJgNG1kQxyssya155P284sNlnS2vGA/YYB0KBsQPS3uMZeYXahoAbqVlyvf8iYoGIQnk/4=,iv:KECeA2bIeHg51qjRH96XBxtqmqJQ86tbTchQ9DLkp8M=,tag:XCIhiKzfTCHpmAJ3Qxdt+A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
  name: credentials-admin
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:MVn14qMdE0c=,iv:rGtQjZ5ewduOc90qUjk3S0ycyrhGuefzPceOY8QIDUg=,tag:5O5aoxc/gUSZkauy3MuXzA==,type:str]
  password: ENC[AES256_GCM,data:3NK2QzfOJFTAq09EiKkKIn9h1fivNLTbTAcE12MClvHQwnw0uHLvSOpF7q/b/cGy,iv:efjjz+ey/G0abnueM2LeCbyv0fa1CUuzM8j7G+A4cwM=,tag:CjMg4CAVm7moeDBFz8iSSA==,type:str]
sops:
  age:
    - recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWdENrUTM5VjFHN0xiaENG
        NVE5WmNaazllVXlJUnZleVc3LzdObGdlWkdVClgvTUFJVW11YnNzNHhWc3hLdktC
        dzZqZkRPdDZWZEpnOUFIZG9iYllycEEKLS0tIHZFYytaZkpGTWhWallwTDBVbSti
        aG02MFR5aHJYZkdmR2Z4OGRURmNSR2sKlM8cM236dm2lpbrV7+ClRnMRrqhMnZQC
        qIF3hzFFBSoddfC/vUxwjYzbXwKyq/j/ZDB6iIHNkXk3SpLretWW+w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-02T21:01:22Z"
  mac: ENC[AES256_GCM,data:qd8T/2i0HXROCBhqmAx/y34mg4UXrtG0uAQzAl8QisO/9vsmq2yxuQKhoJG+Ke7sS1HidZvRx9u/Vkam6wbMp6nipuHOGhKyPsd6ZdJgNG1kQxyssya155P284sNlnS2vGA/YYB0KBsQPS3uMZeYXahoAbqVlyvf8iYoGIQnk/4=,iv:KECeA2bIeHg51qjRH96XBxtqmqJQ86tbTchQ9DLkp8M=,tag:XCIhiKzfTCHpmAJ3Qxdt+A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
