apiVersion: v1
kind: Secret
metadata:
  name: credentials-authentik
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:s/pY/o4rkHq+,iv:ApAh9xXjJw05VTHRJEHvY2JIitbxE8xkYcG+xgXXKoo=,tag:6S3tk9OPQUGYltcLJVtxtw==,type:str]
  password: ENC[AES256_GCM,data:ypbVX70i0g8+QvS2ekmJzi63KAaTQTcNwWCGdVpNuVKGjuZvqbFNBetDl+zMmAAS,iv:oD2S/GLMM9UKCPcZ4BfmhviX97fHoSPfibkzeQlV1xc=,tag:Foykd4Exbb/o1kF0WIrYBg==,type:str]
sops:
  age:
    - recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2aXBIQXR3Wnd5T2Y2SFAr
        SHJaY2JsYU5lV2duN0RiT01ERjhjT01IMkVZCmdXZnE0SVRQcGdVMitrVmhScDFP
        VEluWk5lWDdQTUpiSmRSMHlnU1dyUWcKLS0tIFloREdVekZDRU5TLzNBenptcmxV
        Wm1haERhVUFZYXF2Qktjd2lQSTZyOHMKOB3I6SOTFyhHJCN/V7iAolwNLfROQr9E
        f/kiYdib6E1dhaQJCBYIXCcudNkjMxWksNN4MCTPtPxAP/X3EbwcGQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-21T05:35:04Z"
  mac: ENC[AES256_GCM,data:NU93bfCO3LjcespjFpxWwKhFTW2kLHtxTjNlQ50H3mYnwpdRXIhkuJRikb0GG1PmRBr1r1xkF24Ue9cPeaMMzvK424L5XGWFVx6yxhP2Y1NKO3N0T5+2FZvUYoy8L7B86n+GGZmCQgEvcjtS3pKQp/CvaTME1YgrZBqBrjV/uSc=,iv:IV7XckmgaTw6+vX8k6cc2CxY89j156+H1yhAnv4Ey1k=,tag:KX55mTRbu1Ozc9YfC63NGQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
  name: credentials-admin
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:FHeTOizKirE=,iv:oQdUh8x3F+QCx03vVIWbGGIcAhGb5hiw7/ZTV5jsaXE=,tag:QxL2TM1gSft5LURj0UQpZA==,type:str]
  password: ENC[AES256_GCM,data:R74KdIBLDEZ1z6gEqO5doXhUDRCvBiqUQj27JIU3gN+OJiXmi+sSsJb/mfUEa1i8,iv:DnBJcnPHkcnUycagb890hZUaJETwDOUzufQLlok3S/I=,tag:T3qOGKE4IoNYeAbVC1p3Bg==,type:str]
sops:
  age:
    - recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2aXBIQXR3Wnd5T2Y2SFAr
        SHJaY2JsYU5lV2duN0RiT01ERjhjT01IMkVZCmdXZnE0SVRQcGdVMitrVmhScDFP
        VEluWk5lWDdQTUpiSmRSMHlnU1dyUWcKLS0tIFloREdVekZDRU5TLzNBenptcmxV
        Wm1haERhVUFZYXF2Qktjd2lQSTZyOHMKOB3I6SOTFyhHJCN/V7iAolwNLfROQr9E
        f/kiYdib6E1dhaQJCBYIXCcudNkjMxWksNN4MCTPtPxAP/X3EbwcGQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-21T05:35:04Z"
  mac: ENC[AES256_GCM,data:NU93bfCO3LjcespjFpxWwKhFTW2kLHtxTjNlQ50H3mYnwpdRXIhkuJRikb0GG1PmRBr1r1xkF24Ue9cPeaMMzvK424L5XGWFVx6yxhP2Y1NKO3N0T5+2FZvUYoy8L7B86n+GGZmCQgEvcjtS3pKQp/CvaTME1YgrZBqBrjV/uSc=,iv:IV7XckmgaTw6+vX8k6cc2CxY89j156+H1yhAnv4Ey1k=,tag:KX55mTRbu1Ozc9YfC63NGQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
  name: credentials-backup-s3
stringData:
  ACCESS_KEY_ID: ENC[AES256_GCM,data:XNjQTG9FVEdO0Oh/vedTyxi2M5D8bLm28Ec=,iv:4RgaqyzXBHKKhEUjjub3/iYJcJhi+084MIiw9TP81Ik=,tag:Y1ii8ay1043Jpm9oefZsOA==,type:str]
  ACCESS_SECRET_KEY: ENC[AES256_GCM,data:fDkaGlqkwFh+GubDVLlKjo+6WcYxyjnRv/NPLwCiT4xsqq5mZqBJ2OxDZAWGYHFmjkj8nUPIAndPXnym0TcvGA==,iv:ZJg/+rEfvos3msVOycFoW7eTxa8iVeOVn28AUF5ADr0=,tag:rDLC6alcNOcSz+lDGT0CLQ==,type:str]
  REGION: ENC[AES256_GCM,data:karW8hxoxg==,iv:IMutYeTmn5WixTqVvKP6AvF45uuGfd2JLA5wt3bsuTM=,tag:ioQ6C7XJfAqAALewmNukeA==,type:str]
sops:
  age:
    - recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2aXBIQXR3Wnd5T2Y2SFAr
        SHJaY2JsYU5lV2duN0RiT01ERjhjT01IMkVZCmdXZnE0SVRQcGdVMitrVmhScDFP
        VEluWk5lWDdQTUpiSmRSMHlnU1dyUWcKLS0tIFloREdVekZDRU5TLzNBenptcmxV
        Wm1haERhVUFZYXF2Qktjd2lQSTZyOHMKOB3I6SOTFyhHJCN/V7iAolwNLfROQr9E
        f/kiYdib6E1dhaQJCBYIXCcudNkjMxWksNN4MCTPtPxAP/X3EbwcGQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-21T05:35:04Z"
  mac: ENC[AES256_GCM,data:NU93bfCO3LjcespjFpxWwKhFTW2kLHtxTjNlQ50H3mYnwpdRXIhkuJRikb0GG1PmRBr1r1xkF24Ue9cPeaMMzvK424L5XGWFVx6yxhP2Y1NKO3N0T5+2FZvUYoy8L7B86n+GGZmCQgEvcjtS3pKQp/CvaTME1YgrZBqBrjV/uSc=,iv:IV7XckmgaTw6+vX8k6cc2CxY89j156+H1yhAnv4Ey1k=,tag:KX55mTRbu1Ozc9YfC63NGQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
