---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: authentik-postgres
spec:
  schedule: "0 30 3/12 * * *"
  backupOwnerReference: self
  cluster:
    name: authentik-postgres
