---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: transcode

components:
  - ../../components/sops

resources:
  - ./namespace.yaml
  - ./intel-gpu-top-arc/ks.yaml
  - ./intel-gpu-top-legacy/ks.yaml
  - ./unmanic/ks.yaml
