[env]
_.python.venv = { path = "{{config_root}}/.venv", create = true }
KUBECONFIG = "{{config_root}}/kubeconfig"
SOPS_AGE_KEY_FILE = "{{config_root}}/age.key"
TALOSCONFIG = "{{config_root}}/talos/clusterconfig/talosconfig"

[settings]
experimental = true
python.uv_venv_auto = true

[hooks]
postinstall = "mise run i"
enter = "mise run check-deps"

[tools]
"python" = "3.14.3"
"uv" = "0.10.2"
"pipx:flux-local" = "8.1.0"
"pipx:makejinja" = "2.8.2"
"pipx:asitop" = "latest"
"aqua:budimanjojo/talhelper" = "3.1.4"
"aqua:cilium/cilium-cli" = "0.19.0"
"aqua:cli/cli" = "2.86.0"
"aqua:cue-lang/cue" = "0.15.4"
"aqua:FiloSottile/age" = "1.3.1"
"aqua:fluxcd/flux2" = "2.7.5"
"aqua:getsops/sops" = "3.11.0"
"aqua:go-task/task" = "3.48.0"
"aqua:helm/helm" = "3.20.0"
"aqua:helmfile/helmfile" = "1.2.3"
"aqua:jqlang/jq" = "1.8.1"
"aqua:kubernetes-sigs/kustomize" = "5.7.1"
"kubectl" = "1.35.1"
"aqua:mikefarah/yq" = "4.52.2"
"aqua:siderolabs/talos" = "1.12.3"
"aqua:yannh/kubeconform" = "0.7.0"
"aqua:pre-commit" = "4.5.1"
"aqua:crane" = "latest"

[shell_alias]
k = "kubectl"

[tasks.install]
description = "Install Python dependencies"
alias = "i"
run = "uv pip install -r requirements.txt"

[tasks.check-deps]
description = "Check if Python dependencies need updating"
silent = true
run = '''
  OUTDATED=$(uv pip list --outdated 2>/dev/null)
  if [ -n "$OUTDATED" ]; then
    echo "⚠️  Python dependencies have updates available. Run 'mise install' to update"
  fi
'''
