apiVersion: v1
kind: Secret
metadata:
  name: minio-secrets
stringData:
  MINIO_ROOT_USER: ENC[AES256_GCM,data:SoYdFvc=,iv:+Fp7QBgO8vQbEWZp1dg4gNmjYUGJP+Ie9sL8v500TL0=,tag:0RGvrfvSTWrxeBz7LGC1KA==,type:str]
  MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:XGMynRVF5LH252ht1T80q6RT689XncLFA+RIsgMBdqBsdcgUBKZfz/XqeBI=,iv:jw0zYJAdZUo4NYSftdiCWCaF3S5+wkr/uGNQ4pR2eAE=,tag:eHwuC6KEqo35kK3MIywsYQ==,type:str]
  MINIO_SERVER_URL: ENC[AES256_GCM,data:MyrSJkqjkywStoYE7XgkMmboiui5j/urfb/N5YCf,iv:tU4EbJwtzdEHV8iDlUwhl5o1fgxwfBTQHKCf1aHPdX0=,tag:6b0l0az+9E7OHHVMnmU98A==,type:str]
  MINIO_BROWSER_REDIRECT_URL: ENC[AES256_GCM,data:2Wi7wXMZ0GOeptLvIlcS2ZJrD3UV/78iejXht2la,iv:oIGKK/FhJa86wnA/TSNnPYWooEK8RlAI/nV6yYNKn0w=,tag:6ZQ+EswPKfhQOc3rvIwwgg==,type:str]
  MINIO_IDENTITY_OPENID_DISPLAY_NAME: ENC[AES256_GCM,data:xFKptNPYproZRCTNSRvIAMC+m7A=,iv:Cu70mpGi6hNg8QCVXpnsrRCqIuY2LH613zXIUmuRLM8=,tag:QSct0j6DzWR9OAlntvnhzg==,type:str]
  MINIO_IDENTITY_OPENID_CONFIG_URL: ENC[AES256_GCM,data:1rlHFBFbSBcOi3Ie6WbpP07sb/ZzoVkY7pLc+r7O9pHW86JpZeEDGz5Z8vmWsCiVEEmcsRslK8IAs+d6bzCmXsATFkpOeQS1bk0rgyzvbqynkw==,iv:i7JcIW9VBhWF4KY4u6eDvwPfEtkR6w3xhSoLjfqh0PE=,tag:ZEyVWZEjXcf88cv3r4oCRA==,type:str]
  MINIO_IDENTITY_OPENID_CLIENT_ID: ENC[AES256_GCM,data:pMzZIvc=,iv:Rjh8DRtWOa9aS+snb0ic8K6MNQv2wssfikPREoi9dPE=,tag:2JbA781run/4ilUGBflPgw==,type:str]
  MINIO_IDENTITY_OPENID_CLIENT_SECRET: ENC[AES256_GCM,data:O3G80NviBkYZwGoTeCoPx8y/pf9ZWAz+RQWi4qa6czjm3i6bo9B5FduJnaLvXUIaBrpdedaFS1XF8xqWutlBUnLsyd3q4u8SEQsqHvGzejUPc+K1ZyCxPJnQ4LN9dMlrC43pya1eOnf+c4amp6CqaTcYMCUtpRk7w+TCFFnPb2M=,iv:GG2DKMATTP3D+TWJagPT/HpHFMWJx73tI8p/A83ZEe0=,tag:4A2b9K9N5zHQsAJs/lLbAQ==,type:str]
  MINIO_IDENTITY_OPENID_SCOPES: ENC[AES256_GCM,data:p7ai+rQUUKjUnCtcEXa2X2l+iVg=,iv:jrCdrhctBcJZ47vD5vfV1791YOasEqRKUpcRV1BZZs8=,tag:DNnjTebXlPKsu7TMBHwQRw==,type:str]
sops:
  age:
    - recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDdldCblJEZFpDWHVhSXU4
        S1Y0UllJeHlxOWJwOHFsQ05JU2h4VU1vTFdFCkVWWTFNRkZVTHpjWnk1QlRMNTlX
        Mm04TG5ZWjJ1SWcxdVZydFNIenIySEEKLS0tIEVCaWgrdXZZMTFVdGlyV3JEanUv
        a2dtNGQ4bHNhVGlFYm1aazNMR2xyRjQKptkNZIDRZAcIJI1tPT6YWHccr6PeQU1v
        2Db7HKDlfPIth6rWkJiaEswQjOsOcAMGTDWtGJ9pA764HYMxTZjZvw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-20T21:06:32Z"
  mac: ENC[AES256_GCM,data:7Q2Dx/M2ylOvOehjYvLWSN2/gg3j271NdKLzm3Grw8tK+dh649UnPk9sSh4DTtHB487Fjdg/BsO6OsO6MYSam/1WSPEKQXYn9uknoL8fgnlG/dTDFnjeQ4xNCj6wEZqQR8p1XgrT7dEcjcQlxJJBL+kM6sjrEpf0fD+T4giwtxg=,iv:fGRAtdYMNmTR4swfYwvdFOq3MHplim9u0PEY0ae7RSg=,tag:yVVyneCJpIqwMs2K6Fq0Pw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
