apiVersion: v1
kind: Secret
metadata:
  name: minio-secrets
stringData:
  MINIO_ROOT_USER: ENC[AES256_GCM,data:4maN844=,iv:1d5KGyx0uhCu6HZKn6cpbJ+TvLh48yezum3IH0pit58=,tag:Ishx018V9fFBsKnn4jIlWw==,type:str]
  MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:evlrKX+CO3C5oVTF95GG+1El4RDlk6gTsFGEfLQgvnuVZgpBrdLHQilkEao=,iv:Ra4wAifERjo5/ifHlderedP9B9qlhZt9tFGsVVU3j94=,tag:savUGGTN+S7J8dkL2a2hgQ==,type:str]
  MINIO_OIDC_CLIENT_ID: ENC[AES256_GCM,data:zHtWtf4=,iv:MMYm/iDUaC1QmXCekY0aVrrpVjYxN1wRzQpxPZQGzKg=,tag:7OqgylEnjCRwIb573gWcsg==,type:str]
  MINIO_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:1MlFxYwXcUA3og7vMUag8LYDr2bm/yI7UlgnfXTaHFlcFrxnFcMA/fV9Rvhqza/+R3YIpLD4tDBd5j1SrYsOA+hiNyDZWEA/hb1y6DI4k40d1RMJ5Vy3dzRXK2f6pmODlCDrAepGVd0NaIxzAMdg5kLlJtMeKB8vZG6gkXwnG6M=,iv:pnfmYM5RaGyneA6nU9jEoAJGxow/Tb3tCVFwP8fhFxk=,tag:Qn6dgUz1EaZrpT5tlEQQmw==,type:str]
sops:
  age:
    - recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBcXZtY2l6aHBjRURqY0pV
        QndDQXROaXhTazc5Mmt5bThUUld6MDZkTTF3ClVQNFNMR0JQdlhvY016UEdMUVA1
        VW90aDF4VVNxdDhTZHk4RU8zT1ZPVXcKLS0tIE9VRVpFcXVveFpMWEdiYUZzanMv
        VVkzVElzQ1FEVDJRVnR2eEZEOWJJbkkKdoGcB4mB0q6gHiDSCxCqvV+nPEe3HKFX
        g/LD+kSEUHYnHqiNz3LKMo+F+NQhwMtU00lr5mceb8vworv2DDcYqg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-20T04:41:50Z"
  mac: ENC[AES256_GCM,data:EtN5ZvIE3rRJYuvSKO62MxvGQvJmNzzC3dqwkZUKt67vuz6h9isLsejNp4ulltn4qLwXxlICOkq4ya64ZiTSAfIA7P9w+8dVGEiZTg8BxwXLqsmh5BFWvJJ0mWM7h4zmzGQEzq8neWWXX01w+11MGWKHARpEJe6fiB95eH8kJDc=,iv:xPzWnAAO9viK6pyBS3OKcfmB9wmzM/viDhmQHVsR3xs=,tag:vUDuGA188RpG00JkGctYDg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
