apiVersion: v1
kind: Secret
metadata:
  name: certificate-distribution-inventory
type: Opaque
stringData:
  hosts.yaml: ENC[AES256_GCM,data:xKR5JFVtc83EpsfaliSKOjC/ImMKYvVfV8AFfVLcmKb43aEDPD4V58PPn1zdxtCMDymL9O5DoDZYN9H53qf6HkVk9AgjTucL7w5oxUYiBXl1C4oVcLe0PzcYSVbDfjQ13cF60vA220XRBU2CUe1kAY7RhGhgf2W2hyZ1jcWIuQhFN6B+OYIg7O4VLaQ4G+Mro6uowhJPfXD1MuJApM3A2MewZuAJw4AvXlE3mFScwL2bc6PxpthrCB0smP0pYq3AyXya5dQVx+5o8TEANpETHWrUEfJZuDT51tDpASMBKQxL2TF9GlN5pbXX1Eu28VaFOf3Rs8sL8J9CFesXDgufzwts3D/Z7ogn/ZwVNz24quS5MlKaEwk9ekAv+Dnlin5ZKaYJy1weMWZ7BwZ+6XNdJ3kwKSEdhX4I16HELoDaNL15AGjMSUw3y+IzCTyQG2W3FAG8mWtvC2zOX2ZUH+8t6wCkstUE/UXxNv4WPo9DrI1Fxvkfdo0Ir9BFNsE7JnrxKAA0MsgGEixPcmH2oWGyKZocWSUoB73MTlmepmeDhSi8Qk0lZm/TrX+4jjgxBDA0GQ6TDO5um+M8Drhoj0C+2ISqS8XD5P9rf71E87VAZqD9hoAgJnWHm0QNVH4Qz6bVm1fc+425P+fneRrNGsZcuRWZdtlWfjFV+ckev1x/jdK2VjNW6DIcsf2bIt7VlwFbAvK6K8Z4ERfZijoz1aK6pPg2zCJ2sD6UaHvk9GVfC6QXr2uUYW76jev7G+WqT4FzUUQN9Phq5zcokOxNwsR1aBqHWxua6zrCCbIMNkp7DHn8e6JrwHVJgq+OFCMe2TrL9DzrQ1Aus6Lu1G0Z998IF4gI6sQeAvSbobh3SpqsOOU43xYPNNu9sSLGtXeUnwawFzEfi1PNPeWNvDi3Kq+o3vtreAm83L4Fi46kMQ6vGfGE4jFWOK01Uq7ZmkIoK0ow6rNHTe4wL9xymugvuL+6P8kTYeOOok7e+Lt8Tjuq36WIXfY3cq1+uMuEEzofzufd0XBH2nfEZ7UsW1r91k/BKrpFwzn+FDpAn6rgNgPhble6seuBjegM,iv:vH44sE0cWHQJPaOzla5881dYIl2DrwO0SA3rmEOxkBs=,tag:lFuCHzQFj8cE8+j6NhwPdw==,type:str]
sops:
  age:
    - recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5OWJvYi9sTGVncG03UWNh
        dlZhN0FDMVpyK1l5MWg4Ynk5bEY2RFY4YVZrCjJaQXRvZXdzeWZsRnJFUU5RSXBT
        a0ErakVYWjBiZi9BQkVvNm1MUzY4MVkKLS0tIDBTSXVwL1QwNDJmZ0hrU0oyUHZU
        NmxXQXI1T2grK2dlOGJYa2Z0d293eUEKhDHIHtYqp2EXFSIL8M+vPE3CWRmtPZgE
        eC8ClSt4YXAc1IF+T9puwJdASC+CwY6r8rFW6GMY/viAeApxCIwh1g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-23T16:27:05Z"
  mac: ENC[AES256_GCM,data:lrUv7+d+YoUgiu6lhwUM5JdEM1wzMVCp3yDRy351p1xzoB11cp+jP1jon3TrroD45D9L7zzTxCMlJ5GVJJvF9B0I3Jck2SE94nIy0PJZVzYwKk+Uw3RaGCU6OO6BV9TjaAJRwxGaralfADr7mQkIVUOT6ST89t7PH0LsJZ/KdDA=,iv:XgK5Q4r+vCqkxetJbLOrSQMUjy16I2ccFxSF2sTtWu4=,tag:BmqBjliPhRGMxXHnGDAByA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
