apiVersion: v1
kind: Secret
metadata:
  name: certificate-distribution-email
type: Opaque
stringData:
  host: ENC[AES256_GCM,data:T+GFdFAf+XnROdmk5SemOAEXSbZdq545RHa5ZNbP2FVTHw==,iv:R0AjMhf3Cb7fhHwb6CE7rXdv505/Gyo1mcSfciYtmis=,tag:3xak0Cq7vGWMOkhy/E2ujg==,type:str]
  port: ENC[AES256_GCM,data:ZJwJ,iv:i7nGMjCpUEcuwpV5PHz6e/akXc39ZLVO9OpEV1jokBo=,tag:SbW9fIwdpX7pLTl7QfegQQ==,type:str]
  username: ENC[AES256_GCM,data:ta/8mmpmgiSL9vqvK6KEK2h5Uv0=,iv:95xLqUvjQtcAm1F8EM6KPcZ5kg1kRNz9TqWHG+CiW6U=,tag:jvmYNQsdqZxXqI1W0U9F/w==,type:str]
  password: ENC[AES256_GCM,data:INL9JMuhBBDj7+0jX4Ya9PrewOXHkwSkHllKaTF+QrS0h2kA6zi2vH+yubc=,iv:ufc7oNB9BpwEoIHuq7Y1wgV1q/bwi0pbF/GQVnPWp2k=,tag:6v74t+cBm1Tbyyd6KVeSOw==,type:str]
  to: ENC[AES256_GCM,data:oFWH3AxdMJRVMsZJB5PjcaPnJ3GPkzeE,iv:B1lipOxn3XMtx3bw3+Ya4G0xrj03hWrJl/IPEW8sIA0=,tag:3nBR1NQSjNqNcGjeESkYfw==,type:str]
  from: ENC[AES256_GCM,data:KnpwsHO3Z9fnaFsRkABfHaCBHT3UzLX7,iv:lufUsD6VdxXwdItlhC01ISmOYcsth85RTV6kRi7QpJ8=,tag:/AJFw22jvae0yckXrN06+A==,type:str]
sops:
  age:
    - recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaUjFqZUZ1dWk4YjNyNFAz
        R3VGSCtNcVZjZy9kdk5Jb0J1Rk9TWkRGR0E0CitMNTN3bU12d0ZUdzlpeHUxdS9O
        SWEyZXVubTJqY1pUazRtS3JzbVdwSmMKLS0tIGJ6bXlYbmpQL2VxekI3MjZ2eU1S
        aUZEYWw3QU5ZL0ZXS0hXaTNCOEg5a00K01ImApsyqEVPXNRP5pju8brtMPPHQDBA
        GI/TaUy6ixTAJ2EKHL2MT3MUfMoGe8aE8PluYjaNBqU9Tk1Citkq2Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-23T03:53:25Z"
  mac: ENC[AES256_GCM,data:7S2q1VjZ0y4Ctzl9TPUwEndDwRGxuUv5EMOSjI4aBkU9okfCeEApKb9CiY5lyWGbhTfgz8T67Kjt7UlSvQNgHfG24epV4/Ac2YVzKP7aYJyWKahbDQUA9HL07KN+wNQI7dRz04FrhrOYxlnotscSM6ih2WN7YoRCJZzOlYyHs40=,iv:Jz1sKjbYNwD2KgRIYALHKsc4aIZCe1DAeLzeBsULNVk=,tag:H6BH/vvXWzpNaCfUeAol8A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
