---
apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: intel-i915
spec:
  rules:
    - name: intel.i915
      labels:
        intel.feature.node.kubernetes.io/gpu: "i915-igpu"
        intel.feature.node.kubernetes.io/gpu-gen: "intel-6gen"
      matchFeatures:
        - feature: pci.device
          matchExpressions:
            class:
              op: In
              value:
                - "0300"
                - "0380"
            vendor:
              op: In
              value:
                - "8086"
            device:
              op: In
              value:
                # Skylake - 6th Gen
                - "1926" # Iris Graphics 540
                - "1916" # HD Graphics 520
                - "1921" # HD Graphics 520
                - "191e" # HD Graphics 515
                - "1912" # HD Graphics 530
                - "191b" # HD Graphics 530
                - "191d" # HD Graphics P530
                - "1902" # HD Graphics 510
                - "1906" # HD Graphics 510
                - "190b" # HD Graphics 510
