---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: immich

components:
  - ../../components/sops

resources:
  - ./namespace.yaml
  # - ./redis/ks.yaml
  # - ./ml/ks.yaml
  # - ./server/ks.yaml
