apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:miQ6m1D3Tk+IlABJ+7c3qQ==,iv:g9nCsC3WUtYmV4cQaVozwjNT4brVTbgQ2WHZJ6u4mZM=,tag:sXIYx/h1xSKHaN8wxyEYhA==,type:str]
  SECRET_AWS_REGION: ENC[AES256_GCM,data:itIyqs98YfOC,iv:Varzs8xvL8BkplE2ggo1WcImsSbIZOb0GyWLDxfdkJs=,tag:zdUrwqlfDpFFSUlBodYw4A==,type:str]
  CERTMANAGER_AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:0d/hbDCOQEyKk1tPNQqCZRtFIs4=,iv:85edYocLPSXrZxpks7pmw8o5xqdArtudJ1fH7LI99KM=,tag:wK/OAHI086gXZsCzLmeqWQ==,type:str]
  CERTMANAGER_AWS_SECRET_KEY: ENC[AES256_GCM,data:xdcWjyxYTZdAp2yM6jLE1EOgW1RTlgCzZfG5u4w1yOzg65rqnPduig==,iv:tI/FKHXf2cHAvkawa2dpY4UAAXbe45ksLuZkyy8k3kk=,tag:Lbp2kIqr3poB3ma57fvgdg==,type:str]
  EXTERNALDNS_AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:aW3sCHXV5aGgYDu5xnwmQ9jR4lk=,iv:6A33tl847OfRE6WFzFABNB5HVaLRUwCMtnGpoXxIv78=,tag:XKmDaib/Ff6igGBuknqxIw==,type:str]
  EXTERNALDNS_AWS_SECRET_KEY: ENC[AES256_GCM,data:n/iVcJxIZUg0p5AqAVkXJyTKAf3MBdYQL909bx0PulceBX8290qnbw==,iv:hJ1YUQ0WRq5XBoO3TUq8BZzSdi5268dlcPWCGCn9Uo0=,tag:jyv638Up9fe2wZKwnunC0Q==,type:str]
  CLUSTER_GATEWAY_INTERNAL_ADDR: ENC[AES256_GCM,data:QVoaBz6Yq+D2YTj5,iv:hr6T9UyLHq4HEP3W0lECoMOJQT/TmGKsSjLfFxZED/E=,tag:J43m9CJbYtVdLwnS+SAD0A==,type:str]
  RACKNAS_ADDR: ENC[AES256_GCM,data:7j1IMGxMr2gjK1WnsQ==,iv:iJlM0lX08bdQX5lmx2ztT1rFiXzMOHvmTN+wOT2pITg=,tag:d01NLqLr3iq4iAVUE27+hQ==,type:str]
sops:
  age:
    - recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBINEJMWCszSU9OemdUdFlP
        OUFaeUhmMTd0MTNwVkJQKzJ4ajQzZFYxZkdJClgxRVd1QmVOamMwRU4rOG9wdC8y
        S2lpZmZnRlI0d3lGTjFVN2RrMDU5TFEKLS0tIE92RzBueGNSZEQ3RGhtNFBCTDBI
        dkNFR0NEZTJUcWlXVlVobDViWDlOc3cKbssCTDTy3o8HHG86Kw3hkwGVNiDa5/Li
        CNhe6S35M1JgGGu1rp8WxjcB75qLbCy+HHJNd7P0ImrCp1XDHrRT/g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-31T04:56:38Z"
  mac: ENC[AES256_GCM,data:qqNYyjuIRKWigp52rxak70/k6Yl+v/gB4r0NhxC3c5gbO4yNFHLkjMySsH94wpCREkun5M7bxVYcN5K6Vdy/zAStsrTRjkEdTkM2H+ZUI2X0BNzYY22g20lErTBxtd8r6wm0c72SzaDquv33i3cjWy5Ia9OcVEtOeFiCON2bs6I=,iv:wjc4l4UJd3ntdD70nYpGo3Ue0fUiSDvHps9QI3D0lQY=,tag:JsXCKozPFltSfQZxVWyXdA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
