apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:KISsstvveO3HIHQUfzBH1g==,iv:pCssFFkM14SKV6tKL3GXKD9tYhtt5RzsnumYsNDNO0k=,tag:oCV2a13gN5E7S0PXp78kjQ==,type:str]
  OLD_SECRET_DOMAIN: ENC[AES256_GCM,data:hPUFgL2zyp4jIMZ5vFYboe4=,iv:z+sakZIhOgh2LmFACTpw7dySq1f+MOBDQA3Evg/0giM=,tag:74Fz8f4cWpLisspZ3rGKag==,type:str]
  SECRET_AWS_REGION: ENC[AES256_GCM,data:fAgSw6UX5gdx,iv:XytalJHFwLgV3yc4vewrVpqziSSHZiBl4E3aMIrcSBE=,tag:u59d13EZFXnzTgxpEvVu4Q==,type:str]
  CERTMANAGER_AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:JM1nirTR2M9JjHV8esSCHM54eIM=,iv:KJ2EOn4udEuQwJBrqyo3exyQtCPrI9XK4vOMejVbv88=,tag:DG7Oi2XgcjZieAloivVI7w==,type:str]
  CERTMANAGER_AWS_SECRET_KEY: ENC[AES256_GCM,data:M5t0PeQCr/aLjCbKNVxPSt7A4ts6eIL8N7viuvFkbfwlHlSiYQrPJA==,iv:aXalo48kalJewrTetSFrkMyNsua7YgA5b9sv+jU6d1I=,tag:xGJnXDjGHwSMWIgMzy0ACw==,type:str]
  EXTERNALDNS_AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:lxA05vBPEaIrQJ7kgvMHIpWBBZg=,iv:O/ifsknWO3K1/3LLHn4/g1uY78dglAvpzQeUriL9dwo=,tag:TxvTO+HQa7dcwhWW5QwAhQ==,type:str]
  EXTERNALDNS_AWS_SECRET_KEY: ENC[AES256_GCM,data:mETecxrgmnsPa2axLEbwoc3nYbCYjEpTPazH4rgZM+37INtpgMYnAg==,iv:hb8YMJF6BUMf+s0Gd3PaLfiGHvLFwTerExm/nD1PfsA=,tag:6qQnYtex4uqOkxn2CmpDlA==,type:str]
  EMAIL_HOST: ENC[AES256_GCM,data:n/QYDiV32ZfXEVXUnX1A7i6OXNt6mFpOht9qSwcpAzcXlA==,iv:am4DqvigA6UZpIaV8/QU85LJozOvH2cmfhtTh1l2/Mo=,tag:2tk2FIKwdpbo8PO0jnfDHA==,type:str]
  EMAIL_USERNAME: ENC[AES256_GCM,data:N3C/7mgcyXyt/boCqAfc7kzoq/M=,iv:PXNJcW9Vcn8pafBzxHhn8CA3bTCriY9pFoE6/KDMtGM=,tag:Xqu7zqpRr3o5vltHKRMN7w==,type:str]
  EMAIL_PASSWORD: ENC[AES256_GCM,data:Y9SCs7dUlwfQ3nQqyEKnfP/pe3foV+Y0gthd8QhPA0W350UOfn60iAve09E=,iv:QgZQOgaXcpaEwa2Bjicoo46nki56OnseJFNQ15C2hPs=,tag:KNj4Otz5QAvT0EUfK/fc9w==,type:str]
  EMAIL_FROM: ENC[AES256_GCM,data:TId/050WlDwQHM90beqPAuQq2bXMYoZr,iv:NpTMVY9E5jQhMVklMqy3/AoApYY3QndG14SGGOBlIVA=,tag:SUAVDvacqn70fQOyphheaw==,type:str]
  AWS_LOGIN_ALIAS: ENC[AES256_GCM,data:7ypOaE0Uk5s=,iv:i7WYed9SD3tqdaOi/zYEEqLKYGT/LbAq2ef+aPFp6ck=,tag:Y/rxSiB910IWH3XxSksFQQ==,type:str]
  TIMEZONE: ENC[AES256_GCM,data:Q+WlTc1irgHDM2tuclvK,iv:G7Zkebyz8t7lviU3mVYCKAUdAQuGhpQM3ZCFX6n3WEk=,tag:JmBlNVdX8660GdahnDb/iw==,type:str]
  HTTP_PROXY: ENC[AES256_GCM,data:SVP5CDvY5R+1ih0tub/gQGwoS2wEoNSdJY5JNTi4MitKO+Q8jzHWkpVh1xElUJlFhz9Ki/M=,iv:AkfZCgFhP3Sp5RA24tDAVLIdHSrnYP4jif40ckhUnAA=,tag:ZwJCFYDu1Bct29Xl3SJlgQ==,type:str]
  HTTPs_PROXY: ENC[AES256_GCM,data:xwPB6L78nws+fiu0oDIdAKdr5B3xN+U6FzIekp5xgPuCvChWeBcV3BJG+47BNxFm6vFKJK8=,iv:7npuk6pxSW8eBUijA9AjYEyjEIueFmHTwWUsCb2xKnI=,tag:i9aXP+R6e2/AW3/Lv/ZpFw==,type:str]
  NO_PROXY: ENC[AES256_GCM,data:zaAOHudc2SodvUqFCzWc8JaJrXj6mv11xI1udJqHonyfsSlaKGQNATAjIpZtVMhQRsQOfrCJ1gospnEVwBC4o9Hb49r6UOo=,iv:4ttaSnym92pyrCjYS/jYSPpeyT4szV8o47UMMUwfrNo=,tag:1q1LC794P8KLHhBHh8Lmbw==,type:str]
  ADGUARD_LB_PRIMARY: ENC[AES256_GCM,data:y8GO6PbrzQTv3f2g,iv:KjlS1aeFb1PjuN2oCZvIYuj5sak8fih8SzL0UnB7UBw=,tag:qwrmqfpHXH0+mj7fo7z+kQ==,type:str]
  ADGUARD_LB_SECONDARY: ENC[AES256_GCM,data:ZP0cz6LQUBBT78MJ,iv:xFz6/ssfk5j0mK0vIfHFY2jTRd1K9IG9cnlkAofQ4lw=,tag:dtACK80vxr3EpEByTAq+iQ==,type:str]
  PROXY_LB: ENC[AES256_GCM,data:PZAYzNobm1FrKQ9e,iv:EGYay4+ZotPLopuepuHuZ/eosnjA2JCgCV1hQDY5t8c=,tag:i94nJShiYUT5g/lMGEdRaA==,type:str]
  CNPG_LB: ENC[AES256_GCM,data:nZCNRF1lv8Pn/WTE,iv:u8ki/t2OyswenRJmIWtO8UUXp7xFkQu6AMsSoXPEqmE=,tag:9D/0WQ6rshJu3RNDfnFMrg==,type:str]
  NTPD_LB: ENC[AES256_GCM,data:/Ej29B3rmM6S0ZzK,iv:9+SGctPnknVEmqtBXCUCm8CLPIUn5D7yR/HH1H+6qrQ=,tag:OGU71MUdFmPgoW5LVTmufg==,type:str]
  CLUSTER_GATEWAY_INTERNAL_ADDR: ENC[AES256_GCM,data:j+DzknJXYH5ArwuG,iv:7qpOvHBoKDPYzWGslxLJaYcdkjHtn7bKY3iNmcT/y+c=,tag:FtMq1ZFNBYFNVip5Konqfg==,type:str]
  RACKNAS_ADDR: ENC[AES256_GCM,data:oJauhKf9HTpVtEZwig==,iv:jzn8uRK9D0dX1v43YwAhY2R2MBq+w7O6wSPxVY8UMkA=,tag:dz63xuyIfHBBDEp5K9Ko3Q==,type:str]
  DERPNAS_ADDR: ENC[AES256_GCM,data:rZXLTOVdF+Yp8XDmOg==,iv:ZIRbrhd8RZ36j91F3XLBgI/SoD6Nf0WuNCOZ4bZZ0CU=,tag:ScR9O0WuK8m/HJPQnSafvA==,type:str]
  UDMP_ADDR: ENC[AES256_GCM,data:4L9Nj4prVtrPNfQ=,iv:apMvq+XgozlOqLJ3CuJFmCoiuV9fbUb2r8cH2wbaPIs=,tag:MZWT8KjvXZTACJV5BVN5xQ==,type:str]
  POOL_ADDR: ENC[AES256_GCM,data:G+m5aq6hGmcziCiU1v0=,iv:PFkVYPRlDAZhrE/UrnndC7HlTnWDWlMxJ4IvH9UbX/g=,tag:Z76APnVXD0GlXteSrfmZaw==,type:str]
  FLOOFEATER_ADDR: ENC[AES256_GCM,data:VrqF0L3Bdf5fDIv4t3E=,iv:FldH9baDOCV3t8bto0qH6D2ILVHpUD6mOV6MClmxqjM=,tag:ZzREOHXG9uZmMT8NhP6Lbg==,type:str]
  ROSIE_ADDR: ENC[AES256_GCM,data:9PUWXk97rF5/2NmXZ6Q=,iv:YII9UyISWAiMb5J2Nt6GZBzSvMQEL7iqC3We6H9HGgA=,tag:JdPcgGI8gTdHL1aDbezQpA==,type:str]
  HDHOMERUN_ADDR: ENC[AES256_GCM,data:LuoUHmDZ/q4Q94BkSg==,iv:hIJEftvyDq1+ZbJyYGa7re8wsnhp4+O78J2mFW0s7Y0=,tag:3sqZMwSuPpN6EmjO0c8fpA==,type:str]
  HDRSAMSUNG55_ADDR: ENC[AES256_GCM,data:hfvoL51RjyJcpCrrOEw=,iv:+8vH6U5NaygkbaXaBQoa7Jt5zRsCBp+aWXdCPQZIFPk=,tag:KbyCXWf2zr29KZfgRrTJew==,type:str]
  OCTOPI_ADDR: ENC[AES256_GCM,data:dSOC1sTNn5YUdscicpQ=,iv:2plLOOcFn57T3cbBBpIIWtHPlXkl8IYcxvz7RkKQZ24=,tag:BtxJTVjlGRmxqvKYl9H02Q==,type:str]
  VALETUDO_AUTH: ENC[AES256_GCM,data:FGC3LSQUwXi/IgDpLqPLKDI6I4E9HF3m28j0oLorPVZG2curi7dLFHDwjon3zorHkgk28J8sIKM=,iv:YZoAABaFU1WC3KBddGs85SIWZmY8x9N5BQakiqYGuJ0=,tag:+loYCSrJwU76Lft5dy6h2g==,type:str]
  BACKUP_DESTINATION_PATH_AUTHENTIK: ENC[AES256_GCM,data:EZHYpjS4X39c4Qe83I/SD0luERBq4J7JfTucH3U=,iv:+Nm4M8AOHKNokYmBP7/OJlbyP6yDaO+5iOCOJ4pwxgU=,tag:tMqQIq2tcDpYIl461Gi1DQ==,type:str]
  BACKUP_DESTINATION_PATH_MAIN: ENC[AES256_GCM,data:wENCDGTDMd0aWewNBu3RpxzxVcrsqO9j,iv:mQKQ5lCwQNXiz0fefXhRe/vRlsWUY/YSd0hzqMsDkPs=,tag:Wcalt3eSSg1HMrSQeHt7HA==,type:str]
sops:
  age:
    - recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEZlR6RDRXWTI0WitEb2hm
        WlRQMHNBWU9qU3B0d3hTQ05GcndjOUJFRm5FCkUzcXVJQ0dVQXlZZzR4RDJJWXNu
        UUZqZlJBSnZESEl1ZjNva2M0THRUV3MKLS0tIDhJdDhLanhxODU3YUJXcWtGaURm
        b25sZzMvNkQ2b0tyWmdOUUdLZ1oxU1EKYOA3ylJ5LBV+EANvbza9eOgco52kqx+o
        bJchYrxZGFH+tU4R6iTlHnOxNJFa3+PGdNxaMoj0Dm4F/UMOG/pntQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-21T18:22:57Z"
  mac: ENC[AES256_GCM,data:N5/GgppZJ97NhGcrnjk8KvUreep1dIwXN2Kkr4MRgKSXMtW521GboavCkfepIdWK7+JfSkh3AtN1JV5pu/2shYf5c6fPybwr3vGxopZCkmFhNnx86op1wdR6yUrMuvuNV0Ut4rCku21DTW1qnrHYWs4TEYz8g/jqZL+P+wNn/eA=,iv:otbocHWNSqT2znYdaJ6gpXySijHkyiC5jKErFHLDNZ0=,tag:YLYIhHvUSRIwi7Lj1CtGYA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
