apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:gL1nN7z2u8zVbXC4OXO8hQ==,iv:2fvjgP7gkaf34D8xYHDF+Ee942x5fEbwrLxOIXcS4Zw=,tag:fXdQlsC1at0j8+S6AoAdng==,type:str]
  SECRET_AWS_REGION: ENC[AES256_GCM,data:GhjvJu+6FLeu,iv:/fCycqUN5IOTyVxQOqBXWseJ9DjesOQyg4Cd00Q6NDY=,tag:lGPstBLS9r09hzQnlY3YHw==,type:str]
  CERTMANAGER_AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:qPkhybtI87G12CCX/tv8zbYfOdg=,iv:3ia0h5HonVGK8t620BwiKd8I7fyWAAfUH5e4Y58dRr0=,tag:bdGG+TC/DJCXLpQvlEzSBg==,type:str]
  CERTMANAGER_AWS_SECRET_KEY: ENC[AES256_GCM,data:UvWIIDDK3Y/Sv0B5UvYJ71cCNMQpS19LS+RRu97hl5Wcu+2or2MOSw==,iv:+l5AeDwr6iHutLDQgqv5MY4MDgNRxecJJRbMffohb/Q=,tag:5y/DadULh8ea1C+XOoap1g==,type:str]
  EXTERNALDNS_AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:NJV1rla2XDAks0Czm4j1ZgDgqpM=,iv:CTldY++rEVlkxyjBt85EggX+yTepw/OEOgy4DIqwjhI=,tag:mdh9gPY8vPSsofxAEcG1/w==,type:str]
  EXTERNALDNS_AWS_SECRET_KEY: ENC[AES256_GCM,data:ERp3I1zZzJnVnpTl2+tYE3EVXUugKuTWEbLAf6Xm693yB3ngeIwUPg==,iv:dUkGo6hwsJPUF1hI+DvxffX+l77BVj9JL0ILQhp/L0s=,tag:mgko2UOC1+O+v1459k9RWw==,type:str]
  AWS_LOGIN_ALIAS: ENC[AES256_GCM,data:zCqAThk1NeI=,iv:lwVhAeyM3LmFSbBWs040Tzbjf/TxchmsgEv0Clspqbw=,tag:Vhxm2SrWmzWyb8/Ar83kGw==,type:str]
  TIMEZONE: ENC[AES256_GCM,data:98Te4eA0IIyDlTRvXzRJ,iv:wE9BTJvu9qCYYXFdCAetEVEADQeUSi8cRQBXoUgBSL8=,tag:cCg61RZGqsrDY5ZMPJS/DA==,type:str]
  AUTH_VALIDITY_PERIOD: ENC[AES256_GCM,data:iLMDpnkzeAQ=,iv:UFlxLwNfR1IFIz55A+gpJdk/EVj7q0m+7bllvzrfKFQ=,tag:roeRDxS3KEdOn855s57xGA==,type:str]
  HTTP_PROXY: ENC[AES256_GCM,data:/SKWdzH1xCStmKsSY4Aed31fvTmOHbKYxAuySi5t2M66mvc0S6erEVn4MDvUk9cyPAOOXIo=,iv:fbmk5pZerRPQXZ/xGTogDkYbowOJkKbESy6KM5c9+18=,tag:eXhmCAkDLQC5hxJ66IGlfg==,type:str]
  HTTPs_PROXY: ENC[AES256_GCM,data:o4wHGVdnLF9XO+infBneMFVV4FtN4zsoLJEDEkXNTvbldhWopQT3DM0hMouVpFGDVT6j9Qo=,iv:SxkCuD4a5bG7rR1o3UZLb2X/Q19lyjwpenu+jUzzKcU=,tag:e/b2IJ3DBgZAXFWJIsDC+A==,type:str]
  NO_PROXY: ENC[AES256_GCM,data:1BAVQTl4lNAuIyjx7/XCgdMDHdmW8rwK41/178zg8Rux876oK0eJCJZkAvhFKqLm0ZFFBCwD4j+Uxp7xJLPqrPy/7j/WByk=,iv:b1IAgbd8SzUrKW8esLlEyVtHm4xshJwry6tXmY8+eNo=,tag:7ORv+t6JJ0WRVRAFHCjdyw==,type:str]
  PROXY_LB: ENC[AES256_GCM,data:c7CxjG6LFe6AaR6Y,iv:Qy+oKbJAUcvV4FT22VFKFS8SxIQcHx/y71JTWEYRWoA=,tag:gQhmkm5nbHdpVlrEPTAj/Q==,type:str]
  CNPG_LB: ENC[AES256_GCM,data:wWFxLy7IVZEco88H,iv:B388lpGS/QM4aDbR99ZiqwmPiqHKvib7BpPw1/a8RU4=,tag:0+h7tk/dvcOQ/ssyry2qww==,type:str]
  CLUSTER_GATEWAY_INTERNAL_ADDR: ENC[AES256_GCM,data:eoxY+dVIyogPiRJ6,iv:5ZVTXzwNvZRvraOYYaurpY+TvSlbS3PIq97ma5UXOpU=,tag:J0YrOGY2BXSK5PNKp3wLzQ==,type:str]
  RACKNAS_ADDR: ENC[AES256_GCM,data:1kWWZpCjmcue3T3VQA==,iv:BEFKV/Bm6yH0XnP0VVjioDIQzphLhcDcknw08a/8N4M=,tag:u9Wfj7rgsBwyMpQMBxVFcQ==,type:str]
  DERPNAS_ADDR: ENC[AES256_GCM,data:zqDsFPStKtDkWbgcsQ==,iv:b6oeVXubxO5ZFkHZQXixOHitbmyaMUCBl5WoCyii+Kc=,tag:mdLnryrA0p3vYJLp2Ym1ag==,type:str]
  UDMP_ADDR: ENC[AES256_GCM,data:ypDtQK+iZtLqiQA=,iv:rJaQJspb5BiRN/wx3pSStYjdFQ5JvVxI7Day4ePFnvk=,tag:sSqvld/mevnE9i658+AXlg==,type:str]
  POOL_ADDR: ENC[AES256_GCM,data:rP8ORx32t6MjsDKdUnk=,iv:x+E6W+wOM9ChombE9eXtFWIJK8GlwyiD5eV3zCLxN0w=,tag:mgx246jlDwn6O5Fgas0cGw==,type:str]
  FLOOFEATER_ADDR: ENC[AES256_GCM,data:hc78Ozni9d8XzCzj8iM=,iv:RtRGa+r+Xz7IorbJOIX5kpIyVVFtIe5nC6W5iPay7FE=,tag:6+3XLNSlKzW0hCrrBJHh4g==,type:str]
  ROSIE_ADDR: ENC[AES256_GCM,data:GPk+7AQz7vJkT0/05Dw=,iv:AOnT4iLiw7uI/BS/o+JSKYw3+uSPuLJLy/uUXJ7I4is=,tag:7pLLDjM8KoXxmOkhPmPBEQ==,type:str]
  HDHOMERUN_ADDR: ENC[AES256_GCM,data:c4aAyRzjee23lyZlPw==,iv:9nMh7OW04wOYldFPBMAQL5RnrThR7l/ra3lSC9izt84=,tag:nkGcYk7fKsOg/7DEOaWE+g==,type:str]
  HDRSAMSUNG55_ADDR: ENC[AES256_GCM,data:fu7fTDtqwkt+BZRbr6I=,iv:3GJuwJqZ6t/6Xrngg0i8pLCNSNRriglDXfB45lq+DTQ=,tag:t8TEmFzs4310mjggW/0oSw==,type:str]
  OCTOPI_ADDR: ENC[AES256_GCM,data:9dn8V9xw9A6cjUk7o38=,iv:3Iy7S8gcYKHuI93Qmb83IFaowZN4EpTe31LyJQuARrc=,tag:L8zUcjAKQ7dxSkCp4nbb+A==,type:str]
  VALETUDO_AUTH: ENC[AES256_GCM,data:2AQ+J9cxIS4u3U9hD6p8rS/k3OQMXnRCoKsFskO8e0KnwMbbJq9MtM3jDHfIX8CpGm4AkoHO5OY=,iv:vPN32fsoIUZsyjZ8tY7k7aRAb6XcfET33SFfEN7TUec=,tag:KrmqIkaeheg/vJkF4kIQgQ==,type:str]
sops:
  age:
    - recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPZVhjNEhJQWwxWHJ5Y2lF
        NTlySEdLOWs5U0JTbU5RUzlCUlNFdUtiWVdnCkdvL2JnUjVRemgxMWd3NXJtYlJK
        VUdUNTRTYW51ek5iRHJDUERRYWVkNEkKLS0tIEVuOW1wTTlxMEhocHBsQjFZNFo2
        S2F3aXdWZDBNM1BVaGZWWitPWDdrSmMK0rWPKcVq0j5TaaJSzmsTBgO+p9HeEmir
        JQlSsAtJdVtqzaX0DAT7Jc96ft/Y2CtGu3n8RF4020AtRRriFeLuzQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-25T03:27:33Z"
  mac: ENC[AES256_GCM,data:qhL4F/ysni518QVKVeCtJIgnO9xxy3Eqak0SXmsCZIzN7bb+TzaH5CPKxwF0JPhLnNVmzw2Xkt+fJTPtOzLvKxM+YsQovYoRH9tvFkvrBKNDyFY7DBkSr+ZNvrqVriqCa/k7fMCAL8QquvF53/Q2gBG3XCuU0iaC1n2jI8AJvGA=,iv:uOvImSTwQMNvms0iHAT0Rt3TNnmnxUS4BmasfYJpil4=,tag:02D+8s6aVdDHL93H2Mk80Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
