---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-12h
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "2880"
  fsType: ext4
  dataLocality: best-effort
  migratable: "true"
  replicaAutoBalance: best-effort
  recurringJobSelector: '[{"name":"backup-12h","isGroup":true},{"name":"default","isGroup":true}]'
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-6h
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "2880"
  fsType: ext4
  dataLocality: best-effort
  migratable: "true"
  replicaAutoBalance: best-effort
  recurringJobSelector: '[{"name":"backup-6h","isGroup":true},{"name":"default","isGroup":true}]'
