apiVersion: v1
kind: Secret
metadata:
  name: immich-server-secrets
type: Opaque
stringData:
  DB_URL: ENC[AES256_GCM,data:DbRQxUovIbxxU6v5upub/rPTQ2NEg3dz4A0m6P0YHEDC9XGMXsaXAHebk7s1quewWaMcP0wSB5niSswuZ5IOKGijOq4OuZ884asvtlE2IUkcWIGPJOpIGK0HprX7FKJXr3ZtteUbxATrpRy00mZwnvmXz2d5yTXW3bE70Z8E8n5i7p2vDm8D,iv:8PkOM30w1rImUTycatjmY3GXGQByjH+1xHlCpILRWzU=,tag:UmsUaf5tl6NeOzH/OHMx1Q==,type:str]
  REDIS_HOSTNAME: ENC[AES256_GCM,data:qK5lpEipr0P93KX90571wSZIJxUtPn/6jKLXnhXol3ji4vfdIQ==,iv:Xp9UfyHCXPIzMHBxTAx5StGIgxztmtP7N1H9hYbKA4c=,tag:68/s1kZVFMEPWZi1kWih9w==,type:str]
  REDIS_PORT: ENC[AES256_GCM,data:lUxXOg==,iv:X+ziPSNOo6Naq+LC1vOr2sOE0hsM2kLErEWUiybJbBY=,tag:L1k6YaNc7jWM/E1Axk/5zg==,type:str]
  REDIS_USERNAME: ENC[AES256_GCM,data:oZd8EOOp,iv:2pqeislW+K2CwuuQ3HB9XHzILlCOD0zERYECUtaL8Bw=,tag:3GExodqO5zElgLo8lL6vhA==,type:str]
  REDIS_PASSWORD: ENC[AES256_GCM,data:8pilDak+0dh/IhS1qrL6fzexWf9XC8TrACbiUMGd46DMPBWGJCjvpLl5uv1LSBfEdMq155QfOr5yr8yNUdoZOQ==,iv:RotlNTNqqjDtlEG1JgESdDxd/41vN0Qa5e2bJiIWKkM=,tag:dkA3Q4+olt2i9wbzcGn/LQ==,type:str]
sops:
  age:
    - recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkUE94YXljL0FRckhidGZE
        ZnVrR2F3Si9xVXJ3a0xGQllzVWZVSEhQRGo0CkdOVzRDcE5MTkM0VzJHbTZLcFJY
        a1Z1WlFLVTlONUlVSzZkYlc0SERXakkKLS0tIEhCSnNtcDFVZUFlcS9aanJXQVJQ
        UitMUUZiV2M4MlVleS9NdEtnZnlZbDAKzgclB1D6DT9ItRiW0ntpnssWxRC1uXUB
        mD1zd6u+UCdRtejG24Kfy7TELBUZsl5UXGkKDRes8w7Ug+VjIRgoDg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-01T23:05:49Z"
  mac: ENC[AES256_GCM,data:0RPS3axrxiBfcEk2zPtXPHryWWMxQjCTyzpKiPu/MPAYk1mXI6cWHJTDonMDcIM9eMHmviPHgQtrGPmRN8YIg37kvSoYO8H0ycLPN6qO4JjPAyVi3O7li778nBaI27Ez9eNPJ0vCMeTHHEGgHqHQD63XGgjG6UopnKu1AGl0XVU=,iv:x1e/gwyNwFBcQcYFuVMGvqmGS26qHh73y4BksFShg4E=,tag:ILxFDVm6uw1QZ5r1VpexDw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
