apiVersion: v1
kind: Secret
metadata:
  name: immich-server-secrets
type: Opaque
stringData:
  DB_URL: ENC[AES256_GCM,data:GZzDA27UjFYP952WWXwmbnVp85s8R4y9pE/Yl7btYke1OptMuuVZnrtYWJVaTgwRBV2GwFbwZBhV0kCQ239Zzzo1vvi3BpFiGnEJ3iPFIT49uf1IAN/L6KbkU39lcTgoMDu4QYI4T6m2k9IdL5Zi5bm9uwJCg5eQnU8U6scy8RwTfcO9V4j/aJZ+tFp8dt8JKYAhQXZj8Zy1,iv:YHcvJS+S7cEgGLu6G7Gp9oMK5bu29i7IwaJcwrD09wk=,tag:M3YtNaSzJqCa1ZBnqkXjAw==,type:str]
  REDIS_HOSTNAME: ENC[AES256_GCM,data:qK5lpEipr0P93KX90571wSZIJxUtPn/6jKLXnhXol3ji4vfdIQ==,iv:Xp9UfyHCXPIzMHBxTAx5StGIgxztmtP7N1H9hYbKA4c=,tag:68/s1kZVFMEPWZi1kWih9w==,type:str]
  REDIS_PORT: ENC[AES256_GCM,data:lUxXOg==,iv:X+ziPSNOo6Naq+LC1vOr2sOE0hsM2kLErEWUiybJbBY=,tag:L1k6YaNc7jWM/E1Axk/5zg==,type:str]
  REDIS_USERNAME: ENC[AES256_GCM,data:oZd8EOOp,iv:2pqeislW+K2CwuuQ3HB9XHzILlCOD0zERYECUtaL8Bw=,tag:3GExodqO5zElgLo8lL6vhA==,type:str]
  REDIS_PASSWORD: ENC[AES256_GCM,data:8pilDak+0dh/IhS1qrL6fzexWf9XC8TrACbiUMGd46DMPBWGJCjvpLl5uv1LSBfEdMq155QfOr5yr8yNUdoZOQ==,iv:RotlNTNqqjDtlEG1JgESdDxd/41vN0Qa5e2bJiIWKkM=,tag:dkA3Q4+olt2i9wbzcGn/LQ==,type:str]
sops:
  age:
    - recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkUE94YXljL0FRckhidGZE
        ZnVrR2F3Si9xVXJ3a0xGQllzVWZVSEhQRGo0CkdOVzRDcE5MTkM0VzJHbTZLcFJY
        a1Z1WlFLVTlONUlVSzZkYlc0SERXakkKLS0tIEhCSnNtcDFVZUFlcS9aanJXQVJQ
        UitMUUZiV2M4MlVleS9NdEtnZnlZbDAKzgclB1D6DT9ItRiW0ntpnssWxRC1uXUB
        mD1zd6u+UCdRtejG24Kfy7TELBUZsl5UXGkKDRes8w7Ug+VjIRgoDg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-28T05:02:47Z"
  mac: ENC[AES256_GCM,data:xLFofBLQ23JP5qn4HxHJZU9knw+a2tZg4zarmvaQKwzB9303aWK3FfzCNm8F4SNiacTseILRpI3QCuOyJMdwYhzY4i15aeEt8qwTggvExTGrezxDNTcrUgHbJwrQIKGqlQ0pDPJP+2qagMrdbRN647RLE6BPe83Fubud6OBO76A=,iv:dL3cutA06PeRvdf05ya55IBa08PYBkHkxcwgp7YBTCY=,tag:qHzA+F4l9tB3xnD9rD9Ltg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
