apiVersion: v1
kind: Secret
metadata:
  name: recyclarr-secrets
type: Opaque
stringData:
  RADARR_1080P_APIKEY: ENC[AES256_GCM,data:/EPxyK4EpiCkBIAqTx6ksUhaS9fDO2RJgNP6Z3AqD2w=,iv:SFn/vCKyIMEjlBVcvHWfLhI4CEKBN3H17xf3oZ3OHnk=,tag:UM+ph6xv0fzrzj/4zO7Bdg==,type:str]
  RADARR_2160P_APIKEY: ENC[AES256_GCM,data:BglCgEj+o2g2pNUpaw7Qgt1GMc3q0CH1QlbqXb1HDvk=,iv:7q2CmSbbRJanaMjQ2pptPPeqaEtDbiZdc3L4K9nysXg=,tag:UUXTmk/fMQEdcz+72LlDgw==,type:str]
  RADARR_ANIME_APIKEY: ENC[AES256_GCM,data:MVwCyE2stR6gjQDl1zJhp4KYP85grsrTnEYqEYFs2s0=,iv:EXE/oEL2a7SxDkrUlZd6FpZA1ZQdQHub4FePF+km2Gg=,tag:690eMCIckmxdJUgRt2nrQw==,type:str]
  SONARR_1080P_APIKEY: ENC[AES256_GCM,data:jXdJmnkpGyS8ih7BNQLBOA6Dkgehfl/g0e9k0byUnes=,iv:LAhFrLHeuvhr0ZgCSJZqFInGQ+VPQLNrgHq/EQUSpkk=,tag:D5xZ4Rr/LW/m7zFzUJiz9g==,type:str]
  SONARR_2160P_APIKEY: ENC[AES256_GCM,data:dU+Hllnt7Wuj/wIjG3rVysys4tNb+5VU7F8GzDXITHE=,iv:G3bYSP8IpWiG2+XPb67kCuv65CnV56SaC+Rco+Y/N8c=,tag:fIaD09yZlIH3zqKvVvM/ew==,type:str]
  SONARR_ANIME_APIKEY: ENC[AES256_GCM,data:VwHinotU2RoJ0ejvbRDeB5pWCEpOtpDRUsxefdj4eSY=,iv:mnOpjk+AUyh2tM47oLnzJkQzBbRMGn/4+Sz70awE0XM=,tag:jHi53MegzPVq1OAK2Hnzpg==,type:str]
sops:
  age:
    - recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOUjJlMVZ6b0hNYVFmWC9x
        dzFsOGVyM2lPUFEydkQxZ1o4UmNTSmJ2WUVFCm1pSitKSHloeWlTR1ZjVDIxQjNN
        Y1BxZkdOZXdzQUtEOHZTbGtWRlg0QUEKLS0tIHFNQVhIaUY2VSs3RjU3cFVJemdI
        ZEw1bDc2Wm0wR01DbFNPcGc0UWU3aDAKtTNWffe76VDoDqjKicIsGIFu6KaZxs3k
        pyCcM/JtHMiksmj+xF01HQ4NfNSplMDJeWo/0fzC4udmfDu85WR22g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-17T16:01:06Z"
  mac: ENC[AES256_GCM,data:WaNuwkIVeUvJUq1PoIhKW2f0Dtg/azRLiJR5hCdadoQiAVL3FcuqTkBVpTONL2RZ3RB65DYZzhSR3QDW2iDaUYAutVXJGE+810FNqH5pYVwRjeyMuCrCj7tU3NgmLf1dcveWobnclJDjVIPX0DRPM//+jHk5I1P/901wnMX121I=,iv:QHDKZAA5xOWP2uXKVeUUwR+TnEfhU6L4ujqES4rsaEw=,tag:DtvKYYFPBHAQQnQH1curHA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
