---
apiVersion: v1
kind: Service
metadata:
  name: hyp-samsung55
spec:
  ports:
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP
---
apiVersion: gateway.networking.k8s.io/v1
kind: BackendTLSPolicy
metadata:
  name: hyp-samsung55-tls
spec:
  targetRefs:
    - group: ""
      kind: Service
      name: hyp-samsung55
  validation:
    wellKnownCACertificates: System
    hostname: hyp-samsung55.${SECRET_DOMAIN}
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: hyp-samsung55
  labels:
    kubernetes.io/service-name: hyp-samsung55
addressType: IPv4
endpoints:
  - addresses:
      - ${HDRSAMSUNG55_ADDR}
ports:
  - name: https
    port: 443
    protocol: TCP
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: hyp-samsung55
spec:
  hostnames:
    - hyp-samsung55.${SECRET_DOMAIN}
  parentRefs:
    - name: envoy-internal
      namespace: gateway
      sectionName: https
  rules:
    - backendRefs:
        - name: hyp-samsung55
          port: 443
