---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: network

resources:
  - ./pool.yaml
  - ./floofeater.yaml
  - ./rosie.yaml
  - ./hdhomerun.yaml
  - ./hyp-samsung55.yaml
  - ./octopi.yaml
