---
apiVersion: v1
kind: Service
metadata:
  name: octopi
spec:
  ports:
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP
---
apiVersion: gateway.networking.k8s.io/v1
kind: BackendTLSPolicy
metadata:
  name: octopi-tls
spec:
  targetRefs:
    - group: ""
      kind: Service
      name: octopi
  validation:
    wellKnownCACertificates: System
    hostname: octopi.${SECRET_DOMAIN}
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: octopi
  labels:
    kubernetes.io/service-name: octopi
addressType: IPv4
endpoints:
  - addresses:
      - ${OCTOPI_ADDR}
ports:
  - name: https
    port: 443
    protocol: TCP
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: octopi
spec:
  hostnames:
    - octopi.${SECRET_DOMAIN}
  parentRefs:
    - name: envoy-internal
      namespace: gateway
      sectionName: https
  rules:
    - backendRefs:
        - name: octopi
          port: 443
