---
apiVersion: v1
kind: Service
metadata:
  name: pool
spec:
  ports:
    - name: http
      port: 5150
      targetPort: 5150
      protocol: TCP
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: pool
  labels:
    kubernetes.io/service-name: pool
addressType: IPv4
endpoints:
  - addresses:
      - ${POOL_ADDR}
ports:
  - name: http
    port: 5150
    protocol: TCP
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: pool
spec:
  hostnames:
    - pool.${SECRET_DOMAIN}
  parentRefs:
    - name: envoy-internal
      namespace: gateway
      sectionName: https
  rules:
    - backendRefs:
        - name: pool
          port: 5150
