---
apiVersion: v1
kind: Service
metadata:
  name: pool
spec:
  type: ExternalName
  externalName: ${POOL_ADDR}
  ports:
    - name: http
      port: 5150
      targetPort: 5150
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: floofeater
spec:
  type: ExternalName
  externalName: ${FLOOFEATER_ADDR}
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: rosie
spec:
  type: ExternalName
  externalName: ${ROSIE_ADDR}
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: hdhomerun
spec:
  type: ExternalName
  externalName: ${HDHOMERUN_ADDR}
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: hyp-samsung55
spec:
  type: ExternalName
  externalName: ${HDRSAMSUNG55_ADDR}
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: octopi
spec:
  type: ExternalName
  externalName: ${OCTOPI_ADDR}
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
