---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: udmp
spec:
  endpoints:
    - dnsName: udmp.${SECRET_DOMAIN}
      recordType: A
      targets:
        - ${UDMP_ADDR}
---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: racknas
spec:
  endpoints:
    - dnsName: racknas.${SECRET_DOMAIN}
      recordType: A
      targets:
        - ${RACKNAS_ADDR}
---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: derpnas
spec:
  endpoints:
    - dnsName: derpnas.${SECRET_DOMAIN}
      recordType: A
      targets:
        - ${DERPNAS_ADDR}
---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: pool
spec:
  endpoints:
    - dnsName: pool.${SECRET_DOMAIN}
      recordType: A
      targets:
        - ${POOL_ADDR}
---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: floofeater
spec:
  endpoints:
    - dnsName: floofeater.${SECRET_DOMAIN}
      recordType: A
      targets:
        - ${FLOOFEATER_ADDR}
---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: rosie
spec:
  endpoints:
    - dnsName: rosie.${SECRET_DOMAIN}
      recordType: A
      targets:
        - ${ROSIE_ADDR}
---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: hdhomerun
spec:
  endpoints:
    - dnsName: hdhomerun.${SECRET_DOMAIN}
      recordType: A
      targets:
        - ${HDHOMERUN_ADDR}
---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: hyp-samsung55
spec:
  endpoints:
    - dnsName: hyp-samsung55.${SECRET_DOMAIN}
      recordType: A
      targets:
        - ${HDRSAMSUNG55_ADDR}
---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: octopi
spec:
  endpoints:
    - dnsName: octopi.${SECRET_DOMAIN}
      recordType: A
      targets:
        - ${OCTOPI_ADDR}
