---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: udmp
spec:
  endpoints:
    - dnsName: udmp.${SECRET_DOMAIN}
      recordType: A
      targets:
        - ${UDMP_ADDR}
---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: racknas
spec:
  endpoints:
    - dnsName: racknas.${SECRET_DOMAIN}
      recordType: A
      targets:
        - ${RACKNAS_ADDR}
---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: derpnas
spec:
  endpoints:
    - dnsName: derpnas.${SECRET_DOMAIN}
      recordType: A
      targets:
        - ${DERPNAS_ADDR}
