---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  # - ./bazarr/ks.yaml
  # - ./pinchflat/ks.yaml
  # - ./prowlarr/ks.yaml
  # - ./radarr/ks.yaml
  # - ./radarr-anime/ks.yaml
  # - ./radarr-remux/ks.yaml
  # - ./radarr-trailers/ks.yaml
  # - ./recyclarr/ks.yaml
  - ./sabnzbd/ks.yaml
  - ./sonarr/ks.yaml
  # - ./sonarr-anime/ks.yaml
  # - ./sonarr-remux/ks.yaml
