metadata_dir = "/meta"
data_dir = "/data"
db_engine = "lmdb"
metadata_auto_snapshot_interval = "6h"

replication_factor = 1
compression_level = 2

rpc_bind_addr = "[::]:3901"

[s3_api]
s3_region = "racknas"
api_bind_addr = "[::]:3900"

[admin]
api_bind_addr = "[::]:3903"
