# yamllint disable-line rule:line-length
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-4.6.2/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: radarr-trailers
spec:
  chartRef:
    kind: OCIRepository
    name: radarr-trailers
  interval: 1h
  values:
    controllers:
      radarr-trailers:
        type: cronjob
        cronjob:
          schedule: "10 0,8,16 * * *"
          ttlSecondsAfterFinished: 86400
        pod:
          restartPolicy: OnFailure
        containers:
          app:
            image:
              repository: jauderho/yt-dlp
              tag: 2026.02.04@sha256:a672f1eeb6b749be2cae8379239051309ee971495de3e1eaddff0201b556a60e
            command:
              - /bin/sh
              - /scripts/get_trailers.sh
            envFrom:
              - secretRef:
                  name: radarr-trailers-secrets
            env:
              TZ: ${TIMEZONE}
              http_proxy: ${HTTP_PROXY}
              https_proxy: ${HTTPS_PROXY}
              no_proxy: ${NO_PROXY}
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                memory: 1Gi
    service:
      app:
        enabled: false
    persistence:
      cache:
        type: emptyDir
        medium: Memory
        sizeLimit: 4Gi
        globalMounts:
          - path: /cache
      movies:
        type: nfs
        server: ${RACKNAS_ADDR}
        path: /volume1/media/Movies
        globalMounts:
          - path: /library/Movies
      movies-anime:
        type: nfs
        server: ${RACKNAS_ADDR}
        path: /volume1/media/Movies-Anime
        globalMounts:
          - path: /library/Movies-Anime
      movies-remux:
        type: nfs
        server: ${RACKNAS_ADDR}
        path: /volume1/media/Movies-Remux
        globalMounts:
          - path: /library/Movies-Remux
      scripts:
        type: configMap
        name: radarr-trailers-configmap
        defaultMode: 0775
        globalMounts:
          - path: /scripts/get_trailers.sh
            subPath: get_trailers.sh
            readOnly: true
