apiVersion: v1
kind: Secret
metadata:
  name: radarr-trailers-secrets
type: Opaque
stringData:
  RADARR_APIKEY: ENC[AES256_GCM,data:HRAjyIH/xlou3hadyPXihF919JTk7s1tzLhL2K2h0Uk=,iv:xNRKCQT6SUOYAsPF77MOwWyQ/GAjr0t7D4kpmfyJUNo=,tag:fYV4r0w+C7QWDzjeJPbq0w==,type:str]
  RADARR_URL: ENC[AES256_GCM,data:55Z3biE4xdcIxCi+h6typwDEdsxpJIbMWrrCSObtB1Zci85lFLUpJsTbXzouow==,iv:9Yfivr+Cfgq4n8cx7TgzqAbuvjbs/kT4sWe2KemN6wM=,tag:SsGsHvgnz6cDCsqodyIhAg==,type:str]
  RADARR_ANIME_APIKEY: ENC[AES256_GCM,data:8QMEWaVMb5xA+U3k1m1qHC27q9phflUTrmko/tSz6UQ=,iv:/4hqehrL/E2uho5RkT0MxXqdWXpCs8iS4SYZRPXn6EI=,tag:x4N2jLA3mGpe4aJzDKnBLg==,type:str]
  RADARR_ANIME_URL: ENC[AES256_GCM,data:jBvQIexJUx4FUIkw9dJ92xTfKsVAFbRn4U7drgXpQlGy8uDcbIZ8aGpJS2BgSf5Rmza5cg==,iv:jkOdFT7Q4WzchJ9TgOnmzlBW3qhGBCcX3mpeGozvHhw=,tag:Qm2fZBVgDLhDjQI7IBQVaQ==,type:str]
  RADARR_REMUX_APIKEY: ENC[AES256_GCM,data:n00DLgB7K2AlzzFKv22u3U7thAnH6gkMrpL/L8ZPme4=,iv:+seYlG1/Qhp2v7kXD0wGrnfMsj8ch1arfb+yNUvimsU=,tag:zyKVpIgd/l0zuqNJCSQYkQ==,type:str]
  RADARR_REMUX_URL: ENC[AES256_GCM,data:wKnN+TJpBEhW3cbMbnr7Tpd0g/xK8XsHsfMnPVyxw5Geduhuaobz/nS2j6viGHmuUiHw1A==,iv:08B1+a62Xx5uYvcV3GiNJ5bz+kbFybMFqk5oIFNyw/U=,tag:ZM1X33KhkWOnm3Lve244lg==,type:str]
sops:
  age:
    - recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIWVJVOUJRTU5yeXFyTjJh
        UmlDQ29RL0ROSXl4YnkxQlAyTytQUDExQ3h3CkRURExYamFjekN5S2FOZ0d1RVhO
        VEh4UnN1VnYxbDl0dlpaNHUwMis3bGcKLS0tIHRDNmxkY0F3UWZkalc1UFc5N2Rq
        RHBHaEZ2R1BDWFZYYVkzY0sxNElsT1UKZLqkFiETxbuFkXpStfBPVFTHsfTM7s//
        Zmw6/2HE+09EjKHy9/0Npz/YpHBYu1DcctYIPRkf+N65K+mTDLSNKA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-17T16:50:49Z"
  mac: ENC[AES256_GCM,data:+vbUYwA5pHA6jrhYYTUVuCw0BDOLjYZmAwtnkkAR2OSmSNk/REbi6NuN4xNfJYziOAyy8cAtyFhed/jfDCuh0kUWey5zIYy5CkgtPr4dyBqyMeua6dX026OTYZzOvAYkpxJOvwVS01h1K4yrL5iXu4w8jKZLkq1ICYut7IkwC7M=,iv:PVAeAX05e9aaS0vgEpsMMQNbUQ5iaz2cia/JbpGvYjI=,tag:q9FUbYBbRWHW5ZbG95WH2Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
