---
apiVersion: v1
kind: Secret
metadata:
  name: radarr-trailers-secrets
type: Opaque
stringData:
  RADARR_APIKEY: ""
  RADARR_URL: "http://radarr.downloads.svc.cluster.local:7878"
  RADARR_ANIME_APIKEY: ""
  RADARR_ANIME_URL: "http://radarr-anime.downloads.svc.cluster.local:7878"
  RADARR_REMUX_APIKEY: ""
  RADARR_REMUX_URL: "http://radarr-remux.downloads.svc.cluster.local:7878"
