apiVersion: v1
kind: Secret
metadata:
  name: immich-redis-acl
type: Opaque
stringData:
  users.acl: ENC[AES256_GCM,data:zp+2xkpdlCk2kn8h/8dXdwoG5U9bETJIStK11tCSMCoggIEnn6k4shZv80ONguQlntMsysvR2m6FaIaA73aM+BtoEHGkAtGQN2Ij71bb+U9iTUNRTrBP+P6g+NP5XO6bqUHiVKF4pEhtff7kvug=,iv:9wyup7j13XYrUY4Lfafl9fZJSEY2B9sU0dzZLoKgzck=,tag:lQwxVN5ROrKFezVJbqzYRQ==,type:str]
sops:
  age:
    - recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5QlVaMXM1SnVKdzkvaTJL
        akxpZFdBZDBNcU8xOFllOHM2YkFhOS9HazBZCkZ1Uk42WW9oSkdkU0t0V3NPbkVY
        a0w5K0hDVTg3aWhrTEJFdmFJNVhYdHMKLS0tIGdIejJEQk9LWmh6dUFNdW8vK0ZU
        TWNMOVhIVVBxUmtxdG9uZEJEM0dXb2cKuRp1Ce/5CX+Vok7inpBoeDNcAymZ5IV1
        dHtnWVluBgU532LdGQzYeJSgz+3K5HK5PLPI6MVi6FT2gDWTJEjNfw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-28T05:03:12Z"
  mac: ENC[AES256_GCM,data:RkwqWr+FGdpPSHA1OsfytnzsCEf9TbLcbDNSio2YGlnn2fMzwKRJY+NaQth4ZyThwyOJcQMnhFgKfqUQ9T98fQ9hb02be3cFUNgfAnvdtLLikEVSSZVFThdtgZSQ3EQKboct/blC/p0tidIRwOlKDCO8cUYQPRG/IHD4oLp7iVg=,iv:DdhK6Qt3mHjJpgtcWLvNIcVU9Dp+DHtoKZxYL3ksmRQ=,tag:GsIH2spdeIfO+AYrIQudCA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
