apiVersion: v1
kind: Secret
metadata:
  name: sabnzbd-secrets
type: Opaque
stringData:
  SABNZBD__API_KEY: ENC[AES256_GCM,data:jtLfi5p8yXSCy/TYeaO3s+FdmvsiyB245uPt44RhTXE=,iv:k/K6y33i+rvxf7CReefStpsdhs44FCNFKEi6cu4B0dg=,tag:ShgbuRZ27C5QBQcmubaKxg==,type:str]
  SABNZBD__NZB_KEY: ENC[AES256_GCM,data:ruHyTl+8VvpBMTVXYJ3Fiw1KW1IWsrjnmPFxm4S0Uis=,iv:C2O1jkDyr7rKbnhOfhaez8+Hv8oQAuuNQ00v0D+l8T4=,tag:50rMyaKluYlz6g9sRi4ZSQ==,type:str]
sops:
  age:
    - recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCbWhTeVFDT1JSanl2bWRp
        RkRzQWE5QThqWFBjdmpnQzBwNDlJUVc3TERrCkl2bXdxMkdjMEh3dW51cVFNbjUr
        SEpVMnRZWks1cko0TEROR2IxRjYvRVkKLS0tICs4d0p1OFJ2am9RVUVDQW5ENjJq
        bnlOUC9jeEhjS0Z1bUJlUGI5UTc5ckkKvqc4ayN2RJg4fXFJgcv9q2lcn7ckFX63
        VLOVHsChBUpV/EIbkXVpayqHI9SL/JQOROftCmVvlwlgDqf2Ccj+4w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-16T22:51:15Z"
  mac: ENC[AES256_GCM,data:I6cL9JmKpEyYq4uABQ7aoP3uf5oz+C0O4JFEzBG6Rrkg/BHl/rvumrzfn8iLDqvwXq6TT4TM3CbKwVAehO+nZXrdeDcfurFNUlOLpiL0RVpOLADm1g2hTSunaRRG87nWMqA5WBeQka4SgvRyL4HwDjWx8dWytZiE6rRnkDu1RLs=,iv:MieRUqkE/S3SfqJgtMTamNu97N7ccEnwBUQDbL806mU=,tag:52gzvItbm0ECPHSxjbjuVw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
  name: provider-config
type: Opaque
stringData:
  VPN_SERVICE_PROVIDER: ENC[AES256_GCM,data:LNzRhNwlHFzi,iv:s1Zu7nIEoWHrwVQtquz3XcCsYR7hZp9t6UqNIm9b9xE=,tag:z3odw7EvRr4JnW2YFUVE8A==,type:str]
  VPN_TYPE: ENC[AES256_GCM,data:RGazdzWf6Qiw,iv:yHoIIa+2WpBVYmaM1rnDRttuLHuVnl3fCgW7b1faPM8=,tag:kESBTBxHJAWjr0JkTMkERA==,type:str]
  WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:LsnDsM+ZrvrOdnLo4OfbozMVuoFzpXkgY4g0ihw9kKA7/7lNozE1Ck1IyYA=,iv:vJXxcyHI4b87HhVDk/0fWH1LR+jBw5BhToOQyf/gtnQ=,tag:R0Yw4nxV36pjdG4kAIQQCA==,type:str]
  SERVER_COUNTRIES: ENC[AES256_GCM,data:FAlk7NGk8Ql59r0eQg==,iv:Fer864rnQEKm20Z/WJNKKEOZ5HwYlEZDQdZjr2IgLcY=,tag:d1VdGFXckQb6Q3wOYxUyvw==,type:str]
  SERVER_CITIES: ENC[AES256_GCM,data:t/U2I1vXfklSWJbNbQli46AI9jtE4fhwrmp8j+0=,iv:gyruTeZVfXTBzmtQOFWsFz6sgtCWIeFQ7ZuTbI0ApLk=,tag:opkHSPuGNlp0vzPrrdpXVQ==,type:str]
  STREAM_ONLY: ENC[AES256_GCM,data:duE=,iv:HaKbEmliJQSMsB97R/KZ/BNpBGYNq5RafOrhZaY+QMo=,tag:+00pOTWr6TaKu1BfkQm5aQ==,type:str]
  DOT: ENC[AES256_GCM,data:N+Bh,iv:KOt/Rs7to4LTn9U1wM+NRP6cQkeS4JZgeoQMZwI8Dus=,tag:/jwwJX8LmG1dNBvp2FSvwA==,type:str]
  DNS_KEEP_NAMESERVER: ENC[AES256_GCM,data:tm+N,iv:S+/2UkNkrhbEF5pFhgYW4X0inCP5tbRbYjYR3Y14paI=,tag:EAbN5yk48ZzcMmErodawMA==,type:str]
  DNS_ADDRESS: ENC[AES256_GCM,data:6BNj+dbwly1Y2Q==,iv:zPQVpji8yhL49jmMXhC2cT1UN4VHQa074hNN3QsT3wE=,tag:0GCb8NHOFIfolMMAjgJv9A==,type:str]
  BLOCK_MALICIOUS: ENC[AES256_GCM,data:LU0K,iv:ZvK6d+rpBInZCnxQUNnTw6XXqz8bNhB4eM21w5R+lYw=,tag:w1qlYV3E/kZIz4dz5CNVuA==,type:str]
  FIREWALL_INPUT_PORTS: ENC[AES256_GCM,data:b/vQzUQrKXbJ,iv:wtgwEu53QbB7z0FmngcDYsmXWEqt2oIqRDXxApCtu3Y=,tag:iw1fB0IYqh+TeWFRSXB3FA==,type:str]
  FIREWALL_OUTBOUND_SUBNETS: ENC[AES256_GCM,data:N8YEBLz3SfPSDFnBoa1qUy4+KkHuuHHxr0c3P5DTbKEQ7BbUT2npZvk/CuNAKPjq5x4/EmXgalM=,iv:oxhRscCX5RRkuAtatFNWw4lZQaXb5R4r/SPc1FWoqz0=,tag:2fmBlvX6NGpCPCSsY9eJZA==,type:str]
  FIREWALL_DEBUG: ENC[AES256_GCM,data:180=,iv:7SRTDXeUdsYubZgvcIVGegV+Ih4E3KQBXu2HE5YXqTA=,tag:mq7kLPCnNBlgEPeU8qeTiQ==,type:str]
  HTTPPROXY: ENC[AES256_GCM,data:vlw=,iv:YBqL334P5WVXl6uzA67JbpbsvaLwYXix7RwuP0T3+os=,tag:JyC5rvCjlYT54ejTY+9g3w==,type:str]
  HTTPPROXY_LISTENING_ADDRESS: ENC[AES256_GCM,data:WTTFxts=,iv:zmZsrX2xtYo8tterBEGqofHjNNTDD+a4qKBYLUNFMLU=,tag:02HnmflXVhye90sZuaIIYw==,type:str]
  HTTPPROXY_STEALTH: ENC[AES256_GCM,data:0oQ=,iv:LF/C0JXgJb1L+FnwjujXzvdoTYDHt5m3pzfDOtGXros=,tag:5K4Y1mhd0D3Ch58lGZgkow==,type:str]
  HTTPPROXY_LOG: ENC[AES256_GCM,data:hvs=,iv:ZxxRk5baY2ItBBignRerWbrWAxI8iBbUWARgztiat7w=,tag:ywHTSQ6lMosqagmzexcOPQ==,type:str]
  SHADOWSOCKS: ENC[AES256_GCM,data:FwiU,iv:D4yB4HPI12WuJUGFq/nmWeW6Dv7aZlIcMemCl3Yl0W8=,tag:YIVWgHpUGQHS6fucQZn1Aw==,type:str]
  VERSION_INFORMATION: ENC[AES256_GCM,data:Fu6t,iv:l5vWOFTPrQhqibSGUnDZifs+ErltjlYeI4bUQKtthsQ=,tag:qILv5HGSU7g9u1oeuEA3Iw==,type:str]
sops:
  age:
    - recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCbWhTeVFDT1JSanl2bWRp
        RkRzQWE5QThqWFBjdmpnQzBwNDlJUVc3TERrCkl2bXdxMkdjMEh3dW51cVFNbjUr
        SEpVMnRZWks1cko0TEROR2IxRjYvRVkKLS0tICs4d0p1OFJ2am9RVUVDQW5ENjJq
        bnlOUC9jeEhjS0Z1bUJlUGI5UTc5ckkKvqc4ayN2RJg4fXFJgcv9q2lcn7ckFX63
        VLOVHsChBUpV/EIbkXVpayqHI9SL/JQOROftCmVvlwlgDqf2Ccj+4w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-16T22:51:15Z"
  mac: ENC[AES256_GCM,data:I6cL9JmKpEyYq4uABQ7aoP3uf5oz+C0O4JFEzBG6Rrkg/BHl/rvumrzfn8iLDqvwXq6TT4TM3CbKwVAehO+nZXrdeDcfurFNUlOLpiL0RVpOLADm1g2hTSunaRRG87nWMqA5WBeQka4SgvRyL4HwDjWx8dWytZiE6rRnkDu1RLs=,iv:MieRUqkE/S3SfqJgtMTamNu97N7ccEnwBUQDbL806mU=,tag:52gzvItbm0ECPHSxjbjuVw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
