apiVersion: v1
kind: Secret
metadata:
  name: sabnzbd-secrets
type: Opaque
stringData:
  SABNZBD__API_KEY: ENC[AES256_GCM,data:jpmP05wq8c8XSGZJG725UCOAHAb9fzLFWCsk/Ucn/Ag=,iv:hZyR1U3giZqsg2C3aOshR9k0INpxi6boE8ggjbpJ0HI=,tag:rxj9puEThZFzGrJ9ZDiTAw==,type:str]
  SABNZBD__NZB_KEY: ENC[AES256_GCM,data:/3HvHKGybJxsWBGAJ0re8aiwclbYkDfBlsf/o+Rzvkw=,iv:0qFRq4S6oaczv9w9luF2SYHWGGRmOkL0R0KOQG8Bcgs=,tag:Uqd0t/SI8gF+oK5OL9WEgw==,type:str]
sops:
  age:
    - recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjKzJBWmF5dWJEdWRuQWFN
        YjZvKy8rVlhucGFIdGdhc0htdVpjUWlRNjA0CkIyUjNzZ05xZmN1c1dJcjJMUkw2
        TWw1OGRrQ0M2ZUt2V2loUzBidjFna3MKLS0tIEtWSDBLSFcwNkREZkV1N0RHODJF
        RVBRMEErQ2c3ck96MklNWnF2VXBkY0UKVLaouY/A7IlPgt1SRB6CCAPDmdd4Njo0
        PnCpMg15lNGWZO+zkXiY/BdNQhvkI10PYWk0z+N4/pMPmAaZGHBoyw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-15T05:00:41Z"
  mac: ENC[AES256_GCM,data:56luWuJgcYgx5HjUIChcbZbx1B3glkvJra/XSMkzb2UKKgptWUg8f9g5Jv1BjKe78JKnoD/9yLLBqd55Gt2deqfrry6NaN4HmW48QoE0LRV/lK30JIeVXtiCYl4MH4HJG0AhIFTRJUa3/nQlSUVT+HpfF/FDvKjUtS/Ep0bgDZc=,iv:VivGKk6rFtIqVtMWaoSQ4LdsyqQPK6cQEZY/Hdsk2ok=,tag:DHTu/3nPmoYf6DqyWhHY6w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
  name: primary-conf93
type: Opaque
stringData:
  VPN_ENDPOINT_IP: ENC[AES256_GCM,data:c7OZ/Epz2HDhatFejw==,iv:k33ogkSwEiP89zUk/lKaraoA8BLE05MmkD/l/V5Wa6A=,tag:NaCqsgPStymcwsntG+mOcg==,type:str]
  VPN_ENDPOINT_PORT: ENC[AES256_GCM,data:61cpd68=,iv:fYQK6eza01xnKWDR2SlOI7pyqx+M+h+19THZgPJiVrk=,tag:82MS/I+P30n3tzt4iAyx+A==,type:str]
  WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:oy+uD98Vdid/YjQ=,iv:wlbj4h7UUPg2vAd5akWiWXHML+v1u7q3HjGdNG7Wz6s=,tag:cMLOPGrJAE7AWCzTClljnw==,type:str]
  WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:tuw+emNueq4e+UHQSRKEp73560pgLfgb6hdkOU/wID3AkvX8rLsM7+UtUp4=,iv:yRQangwLzYmrOuiBArpWTKXTmBB7LZVPEHYHipe3b4M=,tag:V5w1JHGj8VQOEWCLBUjxBQ==,type:str]
  WIREGUARD_PUBLIC_KEY: ENC[AES256_GCM,data:pbLfJ07b2K9noUPGZlsCztBLn1fm4kAY3DkmOxSr+gnb48iHhwBXdi0oS0k=,iv:af70VIe+GXbyB+EYMuzOlT/jwJChLN162VTjs7fCSoc=,tag:P5YyvZC3PivVrDzANiXa5A==,type:str]
sops:
  age:
    - recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjKzJBWmF5dWJEdWRuQWFN
        YjZvKy8rVlhucGFIdGdhc0htdVpjUWlRNjA0CkIyUjNzZ05xZmN1c1dJcjJMUkw2
        TWw1OGRrQ0M2ZUt2V2loUzBidjFna3MKLS0tIEtWSDBLSFcwNkREZkV1N0RHODJF
        RVBRMEErQ2c3ck96MklNWnF2VXBkY0UKVLaouY/A7IlPgt1SRB6CCAPDmdd4Njo0
        PnCpMg15lNGWZO+zkXiY/BdNQhvkI10PYWk0z+N4/pMPmAaZGHBoyw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-15T05:00:41Z"
  mac: ENC[AES256_GCM,data:56luWuJgcYgx5HjUIChcbZbx1B3glkvJra/XSMkzb2UKKgptWUg8f9g5Jv1BjKe78JKnoD/9yLLBqd55Gt2deqfrry6NaN4HmW48QoE0LRV/lK30JIeVXtiCYl4MH4HJG0AhIFTRJUa3/nQlSUVT+HpfF/FDvKjUtS/Ep0bgDZc=,iv:VivGKk6rFtIqVtMWaoSQ4LdsyqQPK6cQEZY/Hdsk2ok=,tag:DHTu/3nPmoYf6DqyWhHY6w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
  name: secondary-conf50
type: Opaque
stringData:
  VPN_ENDPOINT_IP: ENC[AES256_GCM,data:9CDVe2l4NvcgorItkkA=,iv:ZFCRr7CrNWVwAo+KVU9taN86NZxY84WdZclYUvQRics=,tag:ync9ZrfkSCgj0PfeHdoLBQ==,type:str]
  VPN_ENDPOINT_PORT: ENC[AES256_GCM,data:6AVka2U=,iv:q3CdW/fBggQLMhQj9kgLezKlbcvLefD0jCR8U6GnR10=,tag:lJcr7y6koK/3gBPxPltHzg==,type:str]
  WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:oy+uD98Vdid/YjQ=,iv:wlbj4h7UUPg2vAd5akWiWXHML+v1u7q3HjGdNG7Wz6s=,tag:cMLOPGrJAE7AWCzTClljnw==,type:str]
  WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:7kAfJD5bwBAe4T94OmQk9Lj4Q9qw99SA9h5aEQPyE0T13Kp0VqIvKZ7avwc=,iv:FiNdwK5QtekEocK1DeaHP0eFXi5BxCbsd6T3sZgbAJk=,tag:QDnGklr762USLlKxrdyaRw==,type:str]
  WIREGUARD_PUBLIC_KEY: ENC[AES256_GCM,data:oxfiRRZ8wsV4o+LLkSeTxeXw2sLstKNx/7YsBHnLuZQMj1kUv9lie8CNoA8=,iv:FloDLLP0cBkeyRCjhTNRqOq0e1s0GkuV38EL2SDhpIk=,tag:wpSKKhujO3R/IFNpTLSCJw==,type:str]
sops:
  age:
    - recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjKzJBWmF5dWJEdWRuQWFN
        YjZvKy8rVlhucGFIdGdhc0htdVpjUWlRNjA0CkIyUjNzZ05xZmN1c1dJcjJMUkw2
        TWw1OGRrQ0M2ZUt2V2loUzBidjFna3MKLS0tIEtWSDBLSFcwNkREZkV1N0RHODJF
        RVBRMEErQ2c3ck96MklNWnF2VXBkY0UKVLaouY/A7IlPgt1SRB6CCAPDmdd4Njo0
        PnCpMg15lNGWZO+zkXiY/BdNQhvkI10PYWk0z+N4/pMPmAaZGHBoyw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-15T05:00:41Z"
  mac: ENC[AES256_GCM,data:56luWuJgcYgx5HjUIChcbZbx1B3glkvJra/XSMkzb2UKKgptWUg8f9g5Jv1BjKe78JKnoD/9yLLBqd55Gt2deqfrry6NaN4HmW48QoE0LRV/lK30JIeVXtiCYl4MH4HJG0AhIFTRJUa3/nQlSUVT+HpfF/FDvKjUtS/Ep0bgDZc=,iv:VivGKk6rFtIqVtMWaoSQ4LdsyqQPK6cQEZY/Hdsk2ok=,tag:DHTu/3nPmoYf6DqyWhHY6w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
