---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wallos-db
  labels:
    recurring-job-group.longhorn.io/backup-24h: enabled
    recurring-job-group.longhorn.io/default: enabled
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
  volumeName: pvc-5b3dc48b-1f3d-4775-b15f-9a73723f24b1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wallos-logos
  labels:
    recurring-job-group.longhorn.io/backup-24h: enabled
    recurring-job-group.longhorn.io/default: enabled
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
  volumeName: pvc-08b732ef-aaa5-4baf-8f30-f53a7a0a5d03
