---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app recyclarr
  namespace: flux-system
spec:
  targetNamespace: downloads
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: sonarr
      namespace: flux-system
    - name: sonarr-anime
      namespace: flux-system
    - name: sonarr-remux
      namespace: flux-system
    - name: radarr
      namespace: flux-system
    - name: radarr-anime
      namespace: flux-system
    - name: radarr-remux
      namespace: flux-system
  path: ./kubernetes/apps/downloads/recyclarr/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substitute: {}
    substituteFrom:
      - kind: Secret
        name: cluster-secrets
