apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  aws-access-key-id: ENC[AES256_GCM,data:7xX0I29gV4o6oMHDFzWsg2Qy30U=,iv:JI4pa+C0W55Joq3ohEp7Zsy1LHiStPiNozTBtnRADH4=,tag:dN2cUOFHLcrWXeLHaHffxQ==,type:str]
  aws-secret-access-key: ENC[AES256_GCM,data:mUnu6WbP4WFgGWPh1N4MSck6UoUGj4vHXINIapkOc/0xwvpSbz6Sxw==,iv:5WwcEcWn1b7LaIZsOrVNRl6/UqpEAidtaqKj2gFpvOc=,tag:RpxB8wWR7o+bR74nfdtgSA==,type:str]
sops:
  age:
    - recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqK3VybU1ZRHM5aVFpVDNr
        ZmxkdXhKVHRxLzRLQVhaVVpIcjBkODJZZnpBCk9PZGRUQVNpaDZFakdaTnlLeWtE
        ekI5MUFLZFdpWThZK3NjZTJuNlp3VEUKLS0tIHpZM0k2c1pPMGJYUFgzaVpEVHc2
        OEJPQWw1M0w2aUUvbnlHN3pGSnhHWE0KVz8hTrR33XFD/oc9ZjRE0qDVKlnORivX
        yPLKjq6LH77gc7LuE6ZpNF+IYLR1ia3BBO8i/lIkSFPaFb3hugOgHw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-12T04:43:07Z"
  mac: ENC[AES256_GCM,data:p22ysPdTm+hDw7eZbdoGAomhdj0q4TtZ3L9lEbYCVFugNvSdwHcp6xe3efevezkL50XQZC2Qx9Lcq7AXGcHmv5EzVoXQjjaJZLMdUFg3/owC9hIRetb5mdnUp4bVK8JNVZjzZMSnd45RqOJ9ATYSVXej9S/MH+wdU4b3AZzSiZA=,iv:4g6eo/MlaQtfvCL944gXiKtpVJqXxSQCnJXOnvJm0Ks=,tag:DPRWbikm3u749S996/M17g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
