---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    server {
      server_name int.${SECRET_DOMAIN};
      listen 8080;
      root /usr/share/nginx/html/;
      index no_index;

      location / {
        autoindex on;
      }

      location ~ /\.git {
        deny all;
      }

      location ~ /README.md {
        deny all;
      }

      location ~ /LICENSE {
        deny all;
      }
    }
