apiVersion: v1
kind: Secret
metadata:
  name: autopulse-secrets
type: Opaque
stringData:
  config.yaml: ENC[AES256_GCM,data:eFmAVhP9SPgOXyUGroyftXBo9kdxhWnHlT7WlZfYl+b3E9/9S92RO2VT606u58EOQSwWTBnofy0ZnkU+abgCB184hMBrexflZafMbpquvUhauFqHznYsLTUeWcCdpIpzNeL1oZzqjthHW4FhX5KPsAi8Rp9O6TnjU49Cl2K589vDsXJQU5nOjW6tRFeP3tgT5zPlwVTWDwIHkEzRc0iatmsHtwIRDxOssreNK22GqUcF5sTe7RjOHU9dUUMK5TChb2CyIXD/jxkzmnAACN+0KuyRQSPSN2BZBc4TEQdPbqFlNvIGiTDU8TV6vS7GYsMdF+lAofYSuoM93CuUZR87fIUAVUarws63HvZXZhSE0hCXFqXZ1m9u2FXQdsHe3ZtYaIN1+LqzAwM3JXwrAOiubMPfJfSOJzzCRw2hoHtVQP6BOOOLdIKXyxpbaHcKDFzj4P7Yh7YOLZjnB1jhaNz1b1+SjY5WgoYHlNc11rToUmFZh5C1565GRl/UclHkrsEY/CHZzUyzdrToxUytmWTznvcP/Cp3BqzliyH06APhbYlaAfKLg+o8hJGQR///4tB3qpAlv5M0pD3p/uAKW83KxVmGBRiIS3uRq4bcf26ICPFsUUdimF/65kfSgieXZ3QdtUBlE848gFxR0CoVCCO3bm4/LF9mY/xCE2npfcJCHQIItZ52ov+9xYyj7hbb9vTZDaUzkDVHHAtcIeiWJc5Ogd6+L3h04G/N2IiothTvPz5sDsosZGSXsAWd734lRseJ6RxuryTPeZI=,iv:lD4mWBjbzA66+1+MsP89zGoD9MQtCOl730D30/ZrppI=,tag:7PV06uyg0tpJw/gWt/1kkg==,type:str]
sops:
  age:
    - recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMZjhabC9Tc2JtZkxkSmVk
        SmdMcDI1eVZVZmxDeExQQnNHT2dSZTMvUldZCis2M293amFKSXVtNXJscm54RUJu
        Nm9LenA4V3p0Umxia2xCYTdIMmgxOEEKLS0tIHhtcEdRbFAwZHpwbXoxa21Ua3Vv
        MTc4SzJXY1ZxeHBpYTlXQUdocEtMaW8KiHQRFcm2Q3E+SA1PPBejudkIoDmNNSLt
        eaEnAVUjjtHm+NZVcEb14X/G4d/xru9jIfR+X/dxkqrirRDHXROdpw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-27T23:11:36Z"
  mac: ENC[AES256_GCM,data:sF69P6eOU3etycSwmShWH6gRHR7jGhFage+bshg/s9GlsM6f+53wDLL+uXBFU96HiZDYJ2kncLxOQpfctQA/NOy0L1SaVSNfzYNjsP3PCjI6+6sGLwm5YR+Pqd1GNzU2PnDz6cIltcqcZYIR8MLGOLy+i2XdmZldNX5DKGz7DW4=,iv:dVvhcKhmEcB2ogeQvynTOPFaLMe4P3Tw+bfFbZYzqS0=,tag:KWk5FUm/ax40LcAgFiFTVw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
