apiVersion: v1
kind: Secret
metadata:
  name: autopulse-secrets
type: Opaque
stringData:
  config.yaml: ENC[AES256_GCM,data:VsNl/w0dLFb4+ICRlYUgbRILLP+L0iVrRAehbMWfTO7uSMs287TMAHx3UW0v/trq/Cw4mN/lIRvu7s26xnOsbAEajePEULCZODPMznd1N65YUWTIknYh3tr5V8gjFMEpxW2cyMa1eAaEQ2Y0YaxKtixAaMGcd/hkQxFYiEuPWTBW4V9BycMFFUXbxBefNu5SoULAoFbpqYtBeOdzSxcKeRzb5uoNPlpn3Uc8cySoC3NL6PELP3NMQ5v9Rc5OqklydmwoTwNZU8Vx3AHgxf+bFxPYdx8M9DCfMc/e2Fi8EwXXsWUs+ttHtFniXEX9ugSAyi6rqg8z2oBTyayQWKY6OCQ/Y+KJnYENmFA7kN6I/cLG9F+oKhp1Nc8lP4/pYXfSWZDA3aI9TXsyHq/nNMBxnuuDtbs0q/k0pUuhyRS0z5Wnvwotz+1gZiC5OBe9I6gGUAvvKF8H44aHHUpDGx/9VZDHw+4kUSsGq3balDwCIoAbj7ZBpiK8srUHnZecOL13bu2GEm1yZKY+FWEl4Len2eATAny6V+w4lloa+EBuDpSzqBByVoMl3fjnhMzLGWLNgf/ra9rlss+GxtVD5RFrbcq6EkMuHBUF0Cux9nC2RIus7Y3LUcsa89N7ZsC7XB7RDJdLkMiUejwxvA8qkR8SICiDNPha7XFLIzMwcArEICbLH53upTo7pSivk/f3KHbN6fE2XP/+LXJCXRwhAgHmXcac90w=,iv:Y56YAeHM1fiaxF0sxSOd3+dn8it50hiXuIvOfYSW+cA=,tag:YA//lFQaiRhdABfesFSP/Q==,type:str]
sops:
  age:
    - recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMZjhabC9Tc2JtZkxkSmVk
        SmdMcDI1eVZVZmxDeExQQnNHT2dSZTMvUldZCis2M293amFKSXVtNXJscm54RUJu
        Nm9LenA4V3p0Umxia2xCYTdIMmgxOEEKLS0tIHhtcEdRbFAwZHpwbXoxa21Ua3Vv
        MTc4SzJXY1ZxeHBpYTlXQUdocEtMaW8KiHQRFcm2Q3E+SA1PPBejudkIoDmNNSLt
        eaEnAVUjjtHm+NZVcEb14X/G4d/xru9jIfR+X/dxkqrirRDHXROdpw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-20T15:43:32Z"
  mac: ENC[AES256_GCM,data:THTU0nGT5S7xNtDhShGPl7zvvDhbnHykHdcUhlGJwrjo3M4AIprIszQpu2xY8mOsm+G08ZOB4V5nZv+WuQ4l1Z/OMwKipuh4tnnANy/DJIUIkrINmJB0fbPIoMlAcmHrs+BndXmTdw4p4b7qZ9nvFB74uUmrFhOxaUigcjYGFHs=,iv:Fx0jDlZif3BzH632EN0W0eUBeUtxOYcQHM+Eq0sfvog=,tag:DXxlE1uaWX6mpJoKTjei1g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
