apiVersion: v1
kind: Secret
metadata:
  name: autopulse-secrets
type: Opaque
stringData:
  config.yaml: ENC[AES256_GCM,data:M5d4MzhgngaQRQIRxasHXE+qDQsi5afPQCIfOnF+/Cp7LjYnQe/u9YhDiq5HFsJCYUfoYEwCWBhZJaEFv7Hr0Eqc2d6ka3g00cBvBd2EONbShnIWqxx1/ujuL38NMd6BlNAfJT9NtBD1UouRI/huhYq6kMYZQYpzJRVCWzxWCtWbGAmsfgTiIdlsfOqdPrHczaVowVBheZmeOj2Y0PAC0h1sudnRaudW+M/7MHFQRM1qo0Jp4UUNypPeWnlGDsXrzZYvfBKuATsE66eWHzBrd5rYJgu2aReQmLinilKp9mo5/aIm493OHNvLx2DJWDDlzPAcnbI8SIPcHbZyKTQ4PPCul61T1PoKv6cn4VsuUKH3Sz/KObEOQa59nlaD93260ea7OyLQpypJ83+/oHSkJ6g3xwWkUAjD4OoAY/hEDJL6rUUwYWbn7MOfeuJ5xTqYU12ORDX6IGxjRA3tS1yCBkqj695UKocNQ7e/DAFBQtw33MzoDHMPfu3OGVdLhsd9lZwIdsmmpy6oi4NIJL8T3FU/el5IHpVUU1U5qOP8NX6t8zJgHici6EwFm71sTrj+5qc4XTs5RtQl0VVDuMPwLUG4jkZt0ucFweKU8LLHpMDlls8ZMbLOglxhXaWv5Eg4HomWgMT6Oc5t1Sdwyr16+6BSIiobbsZYg0kDXCdH2DhvN/DOWD1yPWGGcYCf5dbB+k1bJdfQ8Co+qPmHlT8NhoTpbNfdysBNPA==,iv:bhmpJcYU09tTD4ElAdhu0zjC6eGs2CPQsNeNKarS0XY=,tag:Iw7bhqFa5FS/430YlczYJg==,type:str]
sops:
  age:
    - recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMZjhabC9Tc2JtZkxkSmVk
        SmdMcDI1eVZVZmxDeExQQnNHT2dSZTMvUldZCis2M293amFKSXVtNXJscm54RUJu
        Nm9LenA4V3p0Umxia2xCYTdIMmgxOEEKLS0tIHhtcEdRbFAwZHpwbXoxa21Ua3Vv
        MTc4SzJXY1ZxeHBpYTlXQUdocEtMaW8KiHQRFcm2Q3E+SA1PPBejudkIoDmNNSLt
        eaEnAVUjjtHm+NZVcEb14X/G4d/xru9jIfR+X/dxkqrirRDHXROdpw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-21T03:42:56Z"
  mac: ENC[AES256_GCM,data:iupxLzlYNPsF+cWlq9s9DTmdDusBnpg1G56Nx/5aBl/E30R161KU+3bw/dISBdzmJMViqnILEhIGbkqmQTHsOyN0RpXVOe0JG7NaOcPp3y7CRX5iTBcauIrgP2XtmvilrUmndGtzYoSJDL2Ae0ZpXw7tYHtx+ltxZgCPYVfCUsA=,iv:FRedR5CRfv+lu2o58zaQY6uGegIdZlRhhNN59UE1jtU=,tag:JJJ+/CBp/F2p0+jYPgRZ6Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
