apiVersion: v1
kind: Secret
metadata:
  name: autopulse-secrets
type: Opaque
stringData:
  config.yaml: ENC[AES256_GCM,data:O0KR106/niMxV20NBifewPv/Pw4yLJAZ3YI0V1trkOhn5lfm04NDgCDzm6X3Tha02fUzbxpjavF2Qb6EGbYRJVLcUlV6wsBhB7v+zT9V8PlCN3AnqmYNM2+VUH7SuQUM61SF2VMs5bjzJ7dEAVbHiLOWL6T3JZbQst5U1KcMEiWMnC0QSCCOlqqwiNQ3yrkd540o5D1eaMPdZShNx9WX2QVmyYXHtiU5Sj9TgKfBqz8HyAq9doLiqwrTdjnnYpKl7EVUVBh67sSIQqZBhUF6ZtPOqPokVo+OMRwFjk4jH2wM1BBah0zJOi9JS6iWQq5qTvmND0rqmKp7HTPNRhT2ImPWa3fNNVZfq7ilhkg16UNsBx1huEKnfQKa0NnxfILNXGq3JlshRcZpy5hQHLUjkcz04MLRybsbp4KPBrUA4dwv7LTKQ9YOChtFYaOoazgywrWQ9BqkB6VIdB+UqWPMcThtQZzp4j4ftMEqmibTfyGHvI4fQ3b2nhpPOzlIrwy4F3uT2e8XlfLFi+UZ1k0JqArRmFK+wIYwxxdI544Nh1lVj7ju49RDs1Jf25p0qURLX8IIG3QzsA8rIvM0m0k4CsRiHR+7ZOK6anWdN4bNaEK4/MoeW42oaRR59wviN/E8xi0bJFkkDSYaJLZZytmNqbqq3RPi1S9nMdRJR1LQzlDnKQ5m4+IZAByWjpFtOj7S2c3l7uH0CIcVKAYFLxIIA+2ezed4fjyo8zkj8AgXRoS0reqAARBRVxySikdCoHmXaIrhM/zSpXldRylG+WQhBaXNSq0FW6nNBhusEHEdInMrm6J0dcHWCOlspgOBstQBmbWs51Kh0UN314k79cmmJuJkqDsIctaF3eVkHWHiI/J2y92KFGSBWQO+2lyAQVjyceQ7Q8VJwCfQFwr7lDNtJULtaY56S3UDYtmahY5bNKpJFqHslr/g9wYNIvmBfX1X8IF4mp+atqZJo9u7t0TRFBp+ayf1NdHiffU/kHOWVk9RTq62CgTjiEo8fHxecvAaWO3kO2xwafcdilbalEKO0Uc3TKqP4HYLcLnNMiAdNtF2I5FJrqucpdHSYezyjnyOw9t30hUEwj7mDL28B/yaqpR4ktRPIW1i04CPCCbUKGRlJ0w6bx3YGHhK+AEn7gHwys7MsSIZ2XM6zgIW88XSFvpvEJfhSBoVOj6tVyktsy/nicX+kO5q3Zr96MJPn2NywT5+iYrcnKl1yprGntv+WcDmUS+MXQUDLFQ6WMU35ENekfS5UxnqaJ/S,iv:ctQm0K62hxfdD2OxlLD2ScOgUvsPWVTz9K+ur+qLy64=,tag:WombThom41gNLT6bprnsVA==,type:str]
sops:
  age:
    - recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5M1FqZWcvVjVreFdxZDYz
        d2dadU9yQkRwVlhBNlpzNnY3eUM2OTJGMmtzCkF3M1ordHZFT0d3KzNMVmFtT0VQ
        TXVlN3ZaY2tVQmFFSXhObU5TdmoxUEkKLS0tIC83M0dhenc4Y0VNam1FUWk0RXJy
        c2dZM082L3R3NmxjWFVzUHZ6K3BlL1EKXU/y80m6dkVYvmbNBXW7MG0UL1bc2LoN
        /i9bKZ/DvrByEwEpgyKdjRYDxFT2HefdOAns1GQpRqQnGBhqSo/y1A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-19T23:43:04Z"
  mac: ENC[AES256_GCM,data:oWenaR1DqhrqhbMLlNQupIWH4j3L+PasRhQRQmZOgu8ctcRDzsuMdFWkhz3IBGtjyARDUW0XTNtMmUcJgROrvuwRTRfiJNGSqnwxnJ67qHTSVUARq8/eU0FbtfsRs8iixET3SmZuRqwuCdQlCSW4F3FkWSJGci3kLltzu5JlSsU=,iv:0lFpqvHNh2WECr1wLOyLjLwoTN3eu0zXdrzdiUOjxxg=,tag:hcBmObLgX6v3rRGKVC72SA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
