apiVersion: v1
kind: Secret
metadata:
  name: autopulse-secrets
type: Opaque
stringData:
  config.yaml: ENC[AES256_GCM,data:AfZwBUtn70RsOMVPRQZhN9+q0Vw0XjelwcrJUESQQaOxCMRcKNL2iwBfY6simrC6ceBGrU0BczfZM5BlURDUJWi2pto4qYGx17zE6RvBN661Hqoa7uuy7Rfnr40tZTlG9I9YM1GeRK3bM8kb/+UExgiMG0dYkzG7MvICCh68fqrQRcplWfTeBwNpw8sMbuakuJk1jvpbKRjIT4TQn3n9sy5AnD8j+1oXpsTVVHGds2SZcGd11cXrN0uzZSQFBomq7ptHh0w5YHNopuG0bX5huEgZdVo46HMqCY4/zJ91errnKalsdX4QvibM2TmseC/VADxrBF2iqLotfKensGomTWYrF2bFMPUXXlM8NyjCQkGYLx3v2MvJjOglJZWhhSfdz7Se0Y0NXLKZHkX2IA0H7NuED8I0sO81nK4L6xEohMc5BGZ4Gj4sW9Hz9ciLzk88/l6xvEttOUwYYzV/IzJYrUVdVeo84yCw5MJ1QaiW8kjXukCul44m0bPx/BMKe6c4dILyV7FIbhDym2NGxnNWD6huW3UH7Rhe1CRr0zzdAOlGGtzeRksF8rmrN0vO/nCtpP0igR0jTOoerTkdLiVdK1LorykKO1xjJDTTUB3dBygrHXI8SpIaHBHrn4HXpYfFO2TJGr8oaJqptG5h2un59QJQqOHkk6GX/uhXRwmcWyw3lPkWQ70E0wGaoA+E9a12N3PlwNFP,iv:S/J1mv1XttMO9u2hPKysLOqq+eAb8M0tmwug0Xpiyz8=,tag:JZgE6lgLegTbUNZAD7qbng==,type:str]
sops:
  age:
    - recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMZjhabC9Tc2JtZkxkSmVk
        SmdMcDI1eVZVZmxDeExQQnNHT2dSZTMvUldZCis2M293amFKSXVtNXJscm54RUJu
        Nm9LenA4V3p0Umxia2xCYTdIMmgxOEEKLS0tIHhtcEdRbFAwZHpwbXoxa21Ua3Vv
        MTc4SzJXY1ZxeHBpYTlXQUdocEtMaW8KiHQRFcm2Q3E+SA1PPBejudkIoDmNNSLt
        eaEnAVUjjtHm+NZVcEb14X/G4d/xru9jIfR+X/dxkqrirRDHXROdpw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-20T03:24:32Z"
  mac: ENC[AES256_GCM,data:60wASPNrs1b/GX5rpTitqqEwXrc040SmFT53TSjdthJkVAI5sYeb1DT8pBE5evLQkhv18j3tFY+HhyMMXBPf8l2Lp/urhtdaX6B8zMA4UhLSTJmK05t7Kg6jyCkBXMep4liGMILpCQyG+1On6ubylM/Mvp69xY+WSdtA04dWbP4=,iv:0LTb73k1msgYMzOfKRXpwNXerzqIOo+goiQIXjdaRmA=,tag:ZsBxP3qaIY5wwtfnIQoKSw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
