apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-secret
type: Opaque
stringData:
  PGADMIN_DEFAULT_EMAIL: ENC[AES256_GCM,data:P6gEmDLfJ2gKt8igo9H6kOFr4OXxxjXr,iv:T49RG1uf95IfnGya5I7VDkGeoIVXa6Wz3B8Yinj1UfE=,tag:tsS+VNKP6m7kUcIZSQE6kQ==,type:str]
  PGADMIN_DEFAULT_PASSWORD: ENC[AES256_GCM,data:UckE8wCb4Dt0TvrGvMpkwuD1UfpDYmoWbNAsQXln0E2seVCohN+CYyBlB7PcS8Wd,iv:O8hwR3R10LmtutSHDlrFjiAMccBbbGL5r8+nq9pRxOc=,tag:5B2GfKSZI9xYXQFu2xiZdQ==,type:str]
sops:
  age:
    - recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLVkJjdWg3a1VwZWNERjJk
        Q25BSmVLSmlmRzBEbUNKdG9MbWRzNi9lckU4CjBYRW1QMW4zM2pMTVZGUkZ5Mk5N
        TVo4bllQeE9kQ2dJUk51cmxyc3VNdGMKLS0tIHZwczJLNEI0K04rVyt3UXRJcFRo
        RlhQUWl0TzRBUzNVMUc2YTlhdGp1S0EK2zSnxezL1gARskcOWtpk3T916pk6ywRp
        pTGelAdLNEWcAfCT3BnYLf3GxtESLdyJq6u8nTmG/kjQwEzIqkT5PQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-25T16:47:38Z"
  mac: ENC[AES256_GCM,data:are9b02RaiIzO5/qgPvDrxNmESZXCTr9c8A5t/nKYG+LvvT1UVXhRliK/OLkeI2OqhcB2U7yYK2eTVeDfC5PV8pm2Px8y7060EfgCk95ltA7MR5KjMtyXKkkuniz1MIGb+E8AbnwNpzs9NjvUEP/J8dfnRgZjX2LjkY6D+gktyM=,iv:UjuHnlccHOXNIU/SaYW1qjAjiFUpMZ0cjUDOovhNr2Y=,tag:0nf8sYJ4rGM6n1pFh/S92Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
