---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: speedtest
spec:
  requestBuffer:
    limit: 35Mi
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: speedtest
