# yamllint disable-line rule:line-length
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-4.6.2/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ntpd
spec:
  chartRef:
    kind: OCIRepository
    name: ntpd
  interval: 1h
  values:
    controllers:
      ntpd:
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: cturra/ntp
              tag: latest@sha256:7224d4e7c7833aabbcb7dd70c46c8a8dcccda365314c6db047b9b10403ace3bc
            env:
              TZ: ${TIMEZONE}
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                add: ["SYS_TIME"]
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                memory: 256Mi
    persistence:
      chrony-etc:
        type: emptyDir
        medium: Memory
        globalMounts:
          - path: /etc/chrony
      chrony-run:
        type: emptyDir
        medium: Memory
        globalMounts:
          - path: /run/chrony
      chrony-var-run:
        type: emptyDir
        medium: Memory
        globalMounts:
          - path: /var/run/chrony
      chrony-lib:
        type: emptyDir
        medium: Memory
        globalMounts:
          - path: /var/lib/chrony
    service:
      app:
        controller: ntpd
        type: LoadBalancer
        externalTrafficPolicy: Local
        annotations:
          metallb.io/loadBalancerIPs: ${NTPD_LB}
        ports:
          ntp:
            port: 123
            protocol: UDP
            targetPort: 123
