apiVersion: v1
kind: Secret
metadata:
  name: authentik-secrets
type: Opaque
stringData:
  secret-key: ENC[AES256_GCM,data:6X5xp150PIeaJphPFdkI4IVXFHaibLxz35RIgFfd2IiwVwN9zzq40mF+Okt0hndn+Ok=,iv:xemIkSA0YhxOYUU++jQrFraLAGD3bYmK7OllkHF7vbk=,tag:Fpwj4mBKLGRNFloMbAJyRA==,type:str]
  email-host: ENC[AES256_GCM,data:wEQSRDCHRToA/eNBgoXIwc/NkV2xb0/3ZZTFSG9lBL0fJg==,iv:QKlgLshZ6/KmE9ZSPaLBlLSMBPuEbJ00Otq3FNrP0fg=,tag:NNcDQAKn6l4WkKzeWnDMLQ==,type:str]
  email-username: ENC[AES256_GCM,data:gQBJ5R/zOh2iGG5vNxNVDX2nRxs=,iv:XTMNW4okWx80kpyK11ISxa0g2+0TM9gLvsyvWKniuO8=,tag:67MO0el1AcwG8fV3exoPBg==,type:str]
  email-password: ENC[AES256_GCM,data:pw3t3WFqHWAVMgIsjkY7nRSCchO9ZwYtiCg8Qqgbm+u1cUmJcRF2j2AVUYE=,iv:e5epjoc7+GxRK66nR5JVoHYATsbnMZmlcNsC3kKvGnE=,tag:T7TPawEIep0BVsihK9zrDg==,type:str]
  email-from: ENC[AES256_GCM,data:K7Z6VE4lGl29Yxqqgg8zuRI3gpL9Ds+0,iv:z73uyqYTHQHTqeOZetkjJKTuo0QQPMJWuY4Qk42iPi8=,tag:QQFM7r0m1oBTRr7uC2HmIw==,type:str]
sops:
  age:
    - recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBscy9UZDlVcDFxdlZ0QVpL
        Mnd6WThhWVNmeDAzSXNoeFRoeWNoMWwybDAwCjdaNWNIQWNsRE5zeGR1VXZSZ01o
        T1BZbDhkTlRmQ0lZYVNuVHY5eTVsYk0KLS0tIFVnMmNCYnNSN3hGYkttZ2JGVGpn
        Uit5aEcwNlFwS1dxTUwvRGR2SlNoYkUKkpaPdfWvHSufsDsJTm47HtoEoLsp9St8
        78vg7fJ9Cc9WF1dNdZVVqvvYoutv97iB9Mk51p68uhKV70nWrKMFEw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-02T20:57:48Z"
  mac: ENC[AES256_GCM,data:Dj0IqrmhXSatNvvx0AZneB29Tpb6H2RHZKpPDtn0noDYCj7jAOjRN7/EOaoKkp6hGKAiX/ovo5PYNkh6rSoKX6O6B0uoD2A+ktG/xsIok0cCvCNqlr1ji7dkD5rJDqvcrCgJKEZP1BUf7Op0ANn0FWocRm61WE5y9MAS4PPzD5U=,iv:2XIDzVNuhVQ7P+YbSe8LCp2HHpLQxTNidTRunontO7I=,tag:vE7HE22xw+Z6DG5y7bBVvw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
