apiVersion: v1
kind: Secret
metadata:
  name: credentials-admin
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:GaNmY4z+bI8=,iv:qehBCqFkw+B0lnS74suy/nxskU6sCNrn47Y7tVOFvrs=,tag:IkRLG2rCHnyyk9IK6TqVKA==,type:str]
  password: ENC[AES256_GCM,data:9gURCgPRP9ydD422wFxPjdZnc58GpgXHONR6AiDOKacH9VcNbt1UAdkJb35csVQ/,iv:us2MAYvofUv9PTD5ktOWuCHe7cYz5s6p75nyzjrNddw=,tag:lWNrnkYb7SP7HVIXr4qEhg==,type:str]
sops:
  age:
    - recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3YmczMXBoVHU1WnVsaHFw
        NEdEa2dtbXMrVG5LRDFFM2F2R1FNUWJqTjBRCjBtdVhNM1JseUVybmhPRDhINFMy
        aFBPRDhJT1Z5VUJLOUtLNGxZanNXVXcKLS0tIE1rWmJnNndVQWxndVhxcHJsYlZC
        T01tSW9oTTdBdlBER2xUc0dEMktVN28K25oTxMeweVW3FwJsQa74UgNQwOlLHol/
        AklcPmZoJ+J8rpzoT2vRMDmR8aOo5AFONhNohc3AI4SR/uqAWnHRxg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-25T03:13:02Z"
  mac: ENC[AES256_GCM,data:ULAoR58y4ztDHDS9wHeA6s3pqZJ6+DMcgp+l+dnkOPOxg9dURZ8HKCGC3sqLb74CqJDQYqLo6yGiriOxnZJUxNtFrFszaJKSVmmT3Wrhs24dWVm4A6WtuJFEVZHOzoRwR3sLGhgg+4UuiYI/nP21cX2tE8Sb2oIa7mb08W76DkU=,iv:y4eTlNdoOrcBkh0RGY1Eph+fXuzQpuiAIT+7zfFO6qA=,tag:aec9oryBLFGojGaR1PXtiw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
  name: credentials-hass
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:bD/cMg==,iv:8aZe9Ebj/eS/inJgjmitS1fVGM7SIE2p8SL9DN3Zuyw=,tag:EIJc79mP14fXU8ejJNsRqg==,type:str]
  password: ENC[AES256_GCM,data:h2ZUqP67ZOe6JlUMGmIQVlBMQfoMa52lMAPpX6xBxB9Vx83o8I9Ohb+wgx5TsNn5,iv:Bu0BCcrr6vMVbv9em5gLNxTmNjRXXehns/FOCL8IxzA=,tag:mch5azsIEUqtxG6cUc8Vqw==,type:str]
sops:
  age:
    - recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3YmczMXBoVHU1WnVsaHFw
        NEdEa2dtbXMrVG5LRDFFM2F2R1FNUWJqTjBRCjBtdVhNM1JseUVybmhPRDhINFMy
        aFBPRDhJT1Z5VUJLOUtLNGxZanNXVXcKLS0tIE1rWmJnNndVQWxndVhxcHJsYlZC
        T01tSW9oTTdBdlBER2xUc0dEMktVN28K25oTxMeweVW3FwJsQa74UgNQwOlLHol/
        AklcPmZoJ+J8rpzoT2vRMDmR8aOo5AFONhNohc3AI4SR/uqAWnHRxg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-25T03:13:02Z"
  mac: ENC[AES256_GCM,data:ULAoR58y4ztDHDS9wHeA6s3pqZJ6+DMcgp+l+dnkOPOxg9dURZ8HKCGC3sqLb74CqJDQYqLo6yGiriOxnZJUxNtFrFszaJKSVmmT3Wrhs24dWVm4A6WtuJFEVZHOzoRwR3sLGhgg+4UuiYI/nP21cX2tE8Sb2oIa7mb08W76DkU=,iv:y4eTlNdoOrcBkh0RGY1Eph+fXuzQpuiAIT+7zfFO6qA=,tag:aec9oryBLFGojGaR1PXtiw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
  name: credentials-jellystat
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:9fB8Ir4kC5yb,iv:YuRwc9xKS5Fn4eiRGGJOzA2FWEsBUziYr9k9kvSz+Yg=,tag:qbMCBm3uffSn2NOB1KbpFw==,type:str]
  password: ENC[AES256_GCM,data:9xyThCDbJHn+XsaQLT/3ie0JFH9UG/1uSPuSlYmGkB5wjUJ2/PG7cpcm6a+PHAX4,iv:0StYZa1TLRN17JltXirBpvzFQtqSNcww/6X43Bfe1VA=,tag:C1CskMtRByT9k5YOREwLPQ==,type:str]
sops:
  age:
    - recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3YmczMXBoVHU1WnVsaHFw
        NEdEa2dtbXMrVG5LRDFFM2F2R1FNUWJqTjBRCjBtdVhNM1JseUVybmhPRDhINFMy
        aFBPRDhJT1Z5VUJLOUtLNGxZanNXVXcKLS0tIE1rWmJnNndVQWxndVhxcHJsYlZC
        T01tSW9oTTdBdlBER2xUc0dEMktVN28K25oTxMeweVW3FwJsQa74UgNQwOlLHol/
        AklcPmZoJ+J8rpzoT2vRMDmR8aOo5AFONhNohc3AI4SR/uqAWnHRxg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-25T03:13:02Z"
  mac: ENC[AES256_GCM,data:ULAoR58y4ztDHDS9wHeA6s3pqZJ6+DMcgp+l+dnkOPOxg9dURZ8HKCGC3sqLb74CqJDQYqLo6yGiriOxnZJUxNtFrFszaJKSVmmT3Wrhs24dWVm4A6WtuJFEVZHOzoRwR3sLGhgg+4UuiYI/nP21cX2tE8Sb2oIa7mb08W76DkU=,iv:y4eTlNdoOrcBkh0RGY1Eph+fXuzQpuiAIT+7zfFO6qA=,tag:aec9oryBLFGojGaR1PXtiw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
  name: credentials-firefly
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:P3JqAYJxMw==,iv:4WdWiEgiJFkqtdbEMClM+lgjDUEt/kG3nom/Q/qnY0s=,tag:39YT7TNsJyqxCno/HZKEbA==,type:str]
  password: ENC[AES256_GCM,data:k7T1Gy1KTBlAsUjRzLWOHuEHgnmVM0AINzIOZ8F3TaW7Ru5Sh8QM4m62BNPbPl5F,iv:EJ7dY0duHjnwBpIihUlOnZERbG8T7fgVUgG1gTngR5w=,tag:l+Xxt8LEVhWZ9lQUaJFvuA==,type:str]
sops:
  age:
    - recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3YmczMXBoVHU1WnVsaHFw
        NEdEa2dtbXMrVG5LRDFFM2F2R1FNUWJqTjBRCjBtdVhNM1JseUVybmhPRDhINFMy
        aFBPRDhJT1Z5VUJLOUtLNGxZanNXVXcKLS0tIE1rWmJnNndVQWxndVhxcHJsYlZC
        T01tSW9oTTdBdlBER2xUc0dEMktVN28K25oTxMeweVW3FwJsQa74UgNQwOlLHol/
        AklcPmZoJ+J8rpzoT2vRMDmR8aOo5AFONhNohc3AI4SR/uqAWnHRxg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-25T03:13:02Z"
  mac: ENC[AES256_GCM,data:ULAoR58y4ztDHDS9wHeA6s3pqZJ6+DMcgp+l+dnkOPOxg9dURZ8HKCGC3sqLb74CqJDQYqLo6yGiriOxnZJUxNtFrFszaJKSVmmT3Wrhs24dWVm4A6WtuJFEVZHOzoRwR3sLGhgg+4UuiYI/nP21cX2tE8Sb2oIa7mb08W76DkU=,iv:y4eTlNdoOrcBkh0RGY1Eph+fXuzQpuiAIT+7zfFO6qA=,tag:aec9oryBLFGojGaR1PXtiw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
