apiVersion: v1
kind: Secret
metadata:
  name: credentials-admin
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:K/ZAxNZBWtg=,iv:o23bRNVHPUkWsTfoL2GFqGd/GhtSa0oqJVFJjSCx2Oo=,tag:AyGVVY6PvI5sSTq50CQcWw==,type:str]
  password: ENC[AES256_GCM,data:/VBalydnPSH0nlcRWGgGqHoX9JPa/bC2O2wegmBcbF/fT01pFGjUM8yIEzr7VhU/,iv:HdUINkZQAEnoJHhskZgeWCfA8z8cJ7azSU5sbYQXP2A=,tag:ptj0EJOWAmAIelqUjPqBsA==,type:str]
sops:
  age:
    - recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKeXVPSGgrSFRrKzJKV29r
        eTg1Tm01cGZiVm9Ocm1YWHFjV0dxOVNUUGxNCjdnYmxpVm9VdTFhcDQ4dVZtcWdy
        dm5KTHNselRlYmpXOVdON3YzeFEybkEKLS0tIDFlSTFUemgxa25NY0tDbVhUQUtl
        aUtNK09sWTRjRzF3a3h4ZmViOE9FQTgKphn2oPsgUVEIRnGc2oWjzhKOX/r+CI8k
        LQK0uc9PJs9niXwezwfYtG16XP+pCUGqPthXMKn1p7zIK0ZR2pkNQQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-27T05:11:19Z"
  mac: ENC[AES256_GCM,data:/hgl+fTEfLKfDzbqea9mtaqcunry0y2wktxov/ZtGtQGyWV8ZcekbLfiDIqaN1NUBHY/X7vWFDHL3y7x48KoDn60Gr0cuxXE4btO2dduqLOPsn8czX9Lk8A4IvAr7WjnTwPCpg2GVc+229tvomASL4nLTm0B9QXIKqxyYmJhMxg=,iv:R8C1K+HlLRHAy6xbkAu762RxP2cOGkNseedw3v6Exm4=,tag:yj/aZrE2askB+yu83mmYFg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
  name: credentials-hass
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:CtDs1w==,iv:Lpj+/c/OjagFffY5Eh4FlxoacYXWss5k/FSubPj6cxk=,tag:sO3/Dwil29/wIufVL0FXHw==,type:str]
  password: ENC[AES256_GCM,data:mTu351cxFlCAz9zzJHL9tfrUhlFfx6O3tKet14gwtddDT5bHdFpxXbCE6lbxeqi7,iv:EsGhA62fwazpgK2EiBqAipqd5LUYtktDqTOwjT3oG7U=,tag:mWBdgT9L+5Gz73PE1DMS1g==,type:str]
sops:
  age:
    - recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKeXVPSGgrSFRrKzJKV29r
        eTg1Tm01cGZiVm9Ocm1YWHFjV0dxOVNUUGxNCjdnYmxpVm9VdTFhcDQ4dVZtcWdy
        dm5KTHNselRlYmpXOVdON3YzeFEybkEKLS0tIDFlSTFUemgxa25NY0tDbVhUQUtl
        aUtNK09sWTRjRzF3a3h4ZmViOE9FQTgKphn2oPsgUVEIRnGc2oWjzhKOX/r+CI8k
        LQK0uc9PJs9niXwezwfYtG16XP+pCUGqPthXMKn1p7zIK0ZR2pkNQQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-27T05:11:19Z"
  mac: ENC[AES256_GCM,data:/hgl+fTEfLKfDzbqea9mtaqcunry0y2wktxov/ZtGtQGyWV8ZcekbLfiDIqaN1NUBHY/X7vWFDHL3y7x48KoDn60Gr0cuxXE4btO2dduqLOPsn8czX9Lk8A4IvAr7WjnTwPCpg2GVc+229tvomASL4nLTm0B9QXIKqxyYmJhMxg=,iv:R8C1K+HlLRHAy6xbkAu762RxP2cOGkNseedw3v6Exm4=,tag:yj/aZrE2askB+yu83mmYFg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
  name: credentials-jellystat
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:Q+FeIl6TGL2U,iv:+O07oLTnEsEXK8SQhMdBAjKsuzskYHvS69PDWTDNPKs=,tag:D/wZfvYZ1+N0gUIZSVrZoA==,type:str]
  password: ENC[AES256_GCM,data:fKumRA9PKfBdU8D19BLv3+y4n60H/G828PN73AGIawXivsJtEJlJYcbxhJJPpTZH,iv:CJHqPOKXiCmzGRJBvPH7U5n0MOblMpe2GLPVfBkF70M=,tag:doa3EorQ2/Xnf8PaIRdHxQ==,type:str]
sops:
  age:
    - recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKeXVPSGgrSFRrKzJKV29r
        eTg1Tm01cGZiVm9Ocm1YWHFjV0dxOVNUUGxNCjdnYmxpVm9VdTFhcDQ4dVZtcWdy
        dm5KTHNselRlYmpXOVdON3YzeFEybkEKLS0tIDFlSTFUemgxa25NY0tDbVhUQUtl
        aUtNK09sWTRjRzF3a3h4ZmViOE9FQTgKphn2oPsgUVEIRnGc2oWjzhKOX/r+CI8k
        LQK0uc9PJs9niXwezwfYtG16XP+pCUGqPthXMKn1p7zIK0ZR2pkNQQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-27T05:11:19Z"
  mac: ENC[AES256_GCM,data:/hgl+fTEfLKfDzbqea9mtaqcunry0y2wktxov/ZtGtQGyWV8ZcekbLfiDIqaN1NUBHY/X7vWFDHL3y7x48KoDn60Gr0cuxXE4btO2dduqLOPsn8czX9Lk8A4IvAr7WjnTwPCpg2GVc+229tvomASL4nLTm0B9QXIKqxyYmJhMxg=,iv:R8C1K+HlLRHAy6xbkAu762RxP2cOGkNseedw3v6Exm4=,tag:yj/aZrE2askB+yu83mmYFg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
  name: credentials-firefly
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:Qf3TJTYztA==,iv:3F14zHPrRWHbBnADlWdV6ykbKSKQuTU/ENFSexSWHLA=,tag:R8A/vJczKRFFsbGMFIjcpQ==,type:str]
  password: ENC[AES256_GCM,data:z49F6EZL0ZdPjNd8pSj1fAdBAlBJHJ+6twEfyp0ooc4iQoYa+y03zevd8MyMaYEi,iv:ss+Un2eDrP2DAZbtOneVDEQGzxO4PkS7ZEN0JuDLhPQ=,tag:udz2BPHKH8NiLsBT34LQOQ==,type:str]
sops:
  age:
    - recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKeXVPSGgrSFRrKzJKV29r
        eTg1Tm01cGZiVm9Ocm1YWHFjV0dxOVNUUGxNCjdnYmxpVm9VdTFhcDQ4dVZtcWdy
        dm5KTHNselRlYmpXOVdON3YzeFEybkEKLS0tIDFlSTFUemgxa25NY0tDbVhUQUtl
        aUtNK09sWTRjRzF3a3h4ZmViOE9FQTgKphn2oPsgUVEIRnGc2oWjzhKOX/r+CI8k
        LQK0uc9PJs9niXwezwfYtG16XP+pCUGqPthXMKn1p7zIK0ZR2pkNQQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-27T05:11:19Z"
  mac: ENC[AES256_GCM,data:/hgl+fTEfLKfDzbqea9mtaqcunry0y2wktxov/ZtGtQGyWV8ZcekbLfiDIqaN1NUBHY/X7vWFDHL3y7x48KoDn60Gr0cuxXE4btO2dduqLOPsn8czX9Lk8A4IvAr7WjnTwPCpg2GVc+229tvomASL4nLTm0B9QXIKqxyYmJhMxg=,iv:R8C1K+HlLRHAy6xbkAu762RxP2cOGkNseedw3v6Exm4=,tag:yj/aZrE2askB+yu83mmYFg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
  name: credentials-immich
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:AO+rvwpS,iv:FFP4ffjRHTG+5rQyAg6Lp2Pm3jEJdVkOX+X/bmlEfOA=,tag:n1g/7J0YioZEj+SyIPBjdw==,type:str]
  password: ENC[AES256_GCM,data:s/10u7IuYu7+ePGHkb56vTIAQ4yIm6aJr44JUEhNglFsPNOOxh5uWyLZEKwnqm00,iv:T8aRdzssLnLcQ9UtocrEyor7m50aTCOus8Bcj2zXi6I=,tag:MgO6qJ4f5Z2xSNJW8h7E6Q==,type:str]
sops:
  age:
    - recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKeXVPSGgrSFRrKzJKV29r
        eTg1Tm01cGZiVm9Ocm1YWHFjV0dxOVNUUGxNCjdnYmxpVm9VdTFhcDQ4dVZtcWdy
        dm5KTHNselRlYmpXOVdON3YzeFEybkEKLS0tIDFlSTFUemgxa25NY0tDbVhUQUtl
        aUtNK09sWTRjRzF3a3h4ZmViOE9FQTgKphn2oPsgUVEIRnGc2oWjzhKOX/r+CI8k
        LQK0uc9PJs9niXwezwfYtG16XP+pCUGqPthXMKn1p7zIK0ZR2pkNQQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-27T05:11:19Z"
  mac: ENC[AES256_GCM,data:/hgl+fTEfLKfDzbqea9mtaqcunry0y2wktxov/ZtGtQGyWV8ZcekbLfiDIqaN1NUBHY/X7vWFDHL3y7x48KoDn60Gr0cuxXE4btO2dduqLOPsn8czX9Lk8A4IvAr7WjnTwPCpg2GVc+229tvomASL4nLTm0B9QXIKqxyYmJhMxg=,iv:R8C1K+HlLRHAy6xbkAu762RxP2cOGkNseedw3v6Exm4=,tag:yj/aZrE2askB+yu83mmYFg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
