apiVersion: v1
kind: Secret
metadata:
  name: credentials-admin
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:16D/U+Ukf7Y=,iv:iz1mJbfcKRFLgHyjjxmQ+NjsksGiJhTtGz2eGOxfTb0=,tag:5bkMme9JybM1/KdgvEjr2Q==,type:str]
  password: ENC[AES256_GCM,data:+OqkvAt2rmzSMp4ndkNsMuDpnQsKn/dLfElnAKnG3jArssm4KMjZAasLKIECbHfR,iv:cPuiF2GflgKRrD+qbMQHyIswy6uNEJ/N7FcWrH5oL4k=,tag:OCbwnzermowaRjVIzkH6iA==,type:str]
sops:
  age:
    - recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIN0RyRGphZ1M3enFKbWtU
        L0hGdG54T2I1aDFrUlBQMnVGT29vblZGRWgwCm9nZmRrb2ZMRDl5b0p1UHhvV3lB
        SFBwTTJSUUJIVjJiSVN2OHNYTmZqUTQKLS0tIGRIK0tFLzFTMHRoTVJWa0x0cHJQ
        bUh4cE1acnd0TlRKNEMzRXVTcHFCUlkK8cKWTgxoPOHiyTJH8urKoVhFMwnlNJLq
        NNAuJ5B0C6ktO9aOB9ewddWrw6I5dTCPjZMJLqSzvJ0TFD4C3qqR5w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-21T05:35:13Z"
  mac: ENC[AES256_GCM,data:uh+ZRTsLsxFdgrauIln1Ohzt3Zc1Dza47oH9zmW1VJcRf7K5GSkkGuroYL4rpJ8ojWXZLLYnucphGNpubDQifLkiiNIOWGfm+n+VGRwM2D4HSjm8Fj2Avyikb8CmhWRVv+LVfZ4gKB9YC+5ALAfPa7RPNQ/PHnd7umUMnbinLbw=,iv:NqheABKfF/EVkWhWPwO2W48xq8yQ9hLnsVmDxBnci+s=,tag:am1cXl36injn2gF2gYzZ9w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
  name: credentials-hass
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:bp//uw==,iv:cmj4ZKBekGTYb4D0Z3WSwfPueOSu9vLA2w3nii1LLtw=,tag:VFrqtyyC4piR4P1k0WxSqA==,type:str]
  password: ENC[AES256_GCM,data:EAPOOH7YWHDXoU51+XYvJ+Iu5ixcG/67/kYpoaFli9IBP8VH0vFvCNhavXOsmPNa,iv:pTEUx5eJj861vGYSlMgBDxdP8XYaRr1tUCUOu4O0At8=,tag:6rspc/UdoMRln638y32Fbg==,type:str]
sops:
  age:
    - recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIN0RyRGphZ1M3enFKbWtU
        L0hGdG54T2I1aDFrUlBQMnVGT29vblZGRWgwCm9nZmRrb2ZMRDl5b0p1UHhvV3lB
        SFBwTTJSUUJIVjJiSVN2OHNYTmZqUTQKLS0tIGRIK0tFLzFTMHRoTVJWa0x0cHJQ
        bUh4cE1acnd0TlRKNEMzRXVTcHFCUlkK8cKWTgxoPOHiyTJH8urKoVhFMwnlNJLq
        NNAuJ5B0C6ktO9aOB9ewddWrw6I5dTCPjZMJLqSzvJ0TFD4C3qqR5w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-21T05:35:13Z"
  mac: ENC[AES256_GCM,data:uh+ZRTsLsxFdgrauIln1Ohzt3Zc1Dza47oH9zmW1VJcRf7K5GSkkGuroYL4rpJ8ojWXZLLYnucphGNpubDQifLkiiNIOWGfm+n+VGRwM2D4HSjm8Fj2Avyikb8CmhWRVv+LVfZ4gKB9YC+5ALAfPa7RPNQ/PHnd7umUMnbinLbw=,iv:NqheABKfF/EVkWhWPwO2W48xq8yQ9hLnsVmDxBnci+s=,tag:am1cXl36injn2gF2gYzZ9w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
  name: credentials-jellystat
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:lorwLPGHEcTd,iv:hvtwTxb0sZy4ydW5mWdko6YC1ln3Y4CKsboXcc0RULc=,tag:u/lGwNkaO6hwJOgo/9p7iA==,type:str]
  password: ENC[AES256_GCM,data:/mPoDoLjHxTePIdaedBkspbJfE9FB4BPIiHT8xPxAjobEcuXU6GEbZt/a5KJdZx3,iv:5yvqbwqY+qd/mzJrPXe8dSFSrvvew18/g6jtRaRDEqY=,tag:V1MDWUakIW4vTjYj5zjzBw==,type:str]
sops:
  age:
    - recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIN0RyRGphZ1M3enFKbWtU
        L0hGdG54T2I1aDFrUlBQMnVGT29vblZGRWgwCm9nZmRrb2ZMRDl5b0p1UHhvV3lB
        SFBwTTJSUUJIVjJiSVN2OHNYTmZqUTQKLS0tIGRIK0tFLzFTMHRoTVJWa0x0cHJQ
        bUh4cE1acnd0TlRKNEMzRXVTcHFCUlkK8cKWTgxoPOHiyTJH8urKoVhFMwnlNJLq
        NNAuJ5B0C6ktO9aOB9ewddWrw6I5dTCPjZMJLqSzvJ0TFD4C3qqR5w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-21T05:35:13Z"
  mac: ENC[AES256_GCM,data:uh+ZRTsLsxFdgrauIln1Ohzt3Zc1Dza47oH9zmW1VJcRf7K5GSkkGuroYL4rpJ8ojWXZLLYnucphGNpubDQifLkiiNIOWGfm+n+VGRwM2D4HSjm8Fj2Avyikb8CmhWRVv+LVfZ4gKB9YC+5ALAfPa7RPNQ/PHnd7umUMnbinLbw=,iv:NqheABKfF/EVkWhWPwO2W48xq8yQ9hLnsVmDxBnci+s=,tag:am1cXl36injn2gF2gYzZ9w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
  name: credentials-firefly
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:kavKeGhEQA==,iv:DFLGjazkhgNFYVZ2UZo5zpLdear6qEEwJlUobvbVKgY=,tag:S9KvAxX8ZFCw+yaRHBpang==,type:str]
  password: ENC[AES256_GCM,data:AGG5hsFTsYnCIu7z/guWhULY2NmnBr6RyGTc207JcvRk0dFUwU+/7Z3x1aPE3IRi,iv:blyhMbaF97lu9FleYtKTa6wXvwTcUVd+X1XWNS9ram4=,tag:0DUcUX6tZhMH9Y4yy9pz1A==,type:str]
sops:
  age:
    - recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIN0RyRGphZ1M3enFKbWtU
        L0hGdG54T2I1aDFrUlBQMnVGT29vblZGRWgwCm9nZmRrb2ZMRDl5b0p1UHhvV3lB
        SFBwTTJSUUJIVjJiSVN2OHNYTmZqUTQKLS0tIGRIK0tFLzFTMHRoTVJWa0x0cHJQ
        bUh4cE1acnd0TlRKNEMzRXVTcHFCUlkK8cKWTgxoPOHiyTJH8urKoVhFMwnlNJLq
        NNAuJ5B0C6ktO9aOB9ewddWrw6I5dTCPjZMJLqSzvJ0TFD4C3qqR5w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-21T05:35:13Z"
  mac: ENC[AES256_GCM,data:uh+ZRTsLsxFdgrauIln1Ohzt3Zc1Dza47oH9zmW1VJcRf7K5GSkkGuroYL4rpJ8ojWXZLLYnucphGNpubDQifLkiiNIOWGfm+n+VGRwM2D4HSjm8Fj2Avyikb8CmhWRVv+LVfZ4gKB9YC+5ALAfPa7RPNQ/PHnd7umUMnbinLbw=,iv:NqheABKfF/EVkWhWPwO2W48xq8yQ9hLnsVmDxBnci+s=,tag:am1cXl36injn2gF2gYzZ9w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
  name: credentials-immich
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:48Awp+FQ,iv:4Tnq/NAnnfBEzk92Dc0S3/f44YAs9zKmt3xhM4t82f4=,tag:+OnfTKK3yawvgTo061EdxQ==,type:str]
  password: ENC[AES256_GCM,data:dfCPYb6mTisbl6d1bpoXkFWhPP2IpGlI3mfNEd4ppnSPpZjFzbXrpsFeFPcgZ8er,iv:EpaKydutKIT6eu4PF9ieXMKpqw1e/+Zs5H0UMQLysOQ=,tag:1mqSMv3IiwDR8ZWob0xPug==,type:str]
sops:
  age:
    - recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIN0RyRGphZ1M3enFKbWtU
        L0hGdG54T2I1aDFrUlBQMnVGT29vblZGRWgwCm9nZmRrb2ZMRDl5b0p1UHhvV3lB
        SFBwTTJSUUJIVjJiSVN2OHNYTmZqUTQKLS0tIGRIK0tFLzFTMHRoTVJWa0x0cHJQ
        bUh4cE1acnd0TlRKNEMzRXVTcHFCUlkK8cKWTgxoPOHiyTJH8urKoVhFMwnlNJLq
        NNAuJ5B0C6ktO9aOB9ewddWrw6I5dTCPjZMJLqSzvJ0TFD4C3qqR5w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-21T05:35:13Z"
  mac: ENC[AES256_GCM,data:uh+ZRTsLsxFdgrauIln1Ohzt3Zc1Dza47oH9zmW1VJcRf7K5GSkkGuroYL4rpJ8ojWXZLLYnucphGNpubDQifLkiiNIOWGfm+n+VGRwM2D4HSjm8Fj2Avyikb8CmhWRVv+LVfZ4gKB9YC+5ALAfPa7RPNQ/PHnd7umUMnbinLbw=,iv:NqheABKfF/EVkWhWPwO2W48xq8yQ9hLnsVmDxBnci+s=,tag:am1cXl36injn2gF2gYzZ9w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
  name: credentials-backup-s3
stringData:
  ACCESS_KEY_ID: ENC[AES256_GCM,data:NbZYLLMSMYuhOaZ2gEm60pPnEVx5aAWjsCI=,iv:NpfsaupEPDOqrZYFaqKGRcnywV1RQivthuvk3jOJ49A=,tag:Sc2uxdR2qmBzEEYBkUFw+Q==,type:str]
  ACCESS_SECRET_KEY: ENC[AES256_GCM,data:BYWGT94CiLPoWr0jK+Yo8ejNFJ6HGSUBz+JXOH2syDLMol4CCv3JOItNn32HgGiau9Wl9lvtfkA5Pp7pIGXsUA==,iv:D1kBJCnlermz1PTCNVz6GM/8P+aTwdj++2665V4OccM=,tag:SmSC47kcVlBm6bNptLOTSw==,type:str]
  REGION: ENC[AES256_GCM,data:u2AA0aeIRg==,iv:pg4YoZuW4kVaQtHQmPm5lCjcX4DSqL4dLlruvlSKQAM=,tag:z09/UsxE8Fdx5/WZEO7vCA==,type:str]
sops:
  age:
    - recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIN0RyRGphZ1M3enFKbWtU
        L0hGdG54T2I1aDFrUlBQMnVGT29vblZGRWgwCm9nZmRrb2ZMRDl5b0p1UHhvV3lB
        SFBwTTJSUUJIVjJiSVN2OHNYTmZqUTQKLS0tIGRIK0tFLzFTMHRoTVJWa0x0cHJQ
        bUh4cE1acnd0TlRKNEMzRXVTcHFCUlkK8cKWTgxoPOHiyTJH8urKoVhFMwnlNJLq
        NNAuJ5B0C6ktO9aOB9ewddWrw6I5dTCPjZMJLqSzvJ0TFD4C3qqR5w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-21T05:35:13Z"
  mac: ENC[AES256_GCM,data:uh+ZRTsLsxFdgrauIln1Ohzt3Zc1Dza47oH9zmW1VJcRf7K5GSkkGuroYL4rpJ8ojWXZLLYnucphGNpubDQifLkiiNIOWGfm+n+VGRwM2D4HSjm8Fj2Avyikb8CmhWRVv+LVfZ4gKB9YC+5ALAfPa7RPNQ/PHnd7umUMnbinLbw=,iv:NqheABKfF/EVkWhWPwO2W48xq8yQ9hLnsVmDxBnci+s=,tag:am1cXl36injn2gF2gYzZ9w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
