---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hajimari

components:
  - ../../components/sops

resources:
  - ./namespace.yaml
  # - ./hajimari/ks.yaml  # Uncomment after restoring the volume
