apiVersion: v1
kind: Secret
metadata:
  name: pinchflat-autopulse-secrets
type: Opaque
stringData:
  AUTOPULSE_USERNAME: ENC[AES256_GCM,data:rhe9OQ==,iv:zsyDeXjz5xd3UQhdh8nDGhzrCbFhguG3Bm1SWRHEnIM=,tag:4Pp6DXZvNgwCiMFJBVPSvw==,type:str]
  AUTOPULSE_PASSWORD: ENC[AES256_GCM,data:qs3C6xkeECSM6hQaSOetl5BCoALaaaS+0P0XqDuISCU=,iv:IheWjI0an5n1+nqUYf+SIIcmioZ821uIP1RM5dke3xo=,tag:gmLwGlGpNo+Rdprow9jaug==,type:str]
sops:
  age:
    - recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzU3RLekdmRlM3NFdHM2I0
        bkJLekZRc0ZpbGVtYU1SS3BCcklLbitJTVYwCklqT0ZVcG1oVXJlUHhaVXQ5ZWMz
        NFU2NjJ1SWxoZ0VURTNIeWVSdWptUUUKLS0tIG5takZDY0RjM0xRcEFGNlZ1VzBH
        U3BsNlhzSVU4cHlCUjBXWmkvZ0FxczQKlP1QAyu8Y0MDVWJyHq3QEuVqRslNJGBd
        O6w0cSpouBu22YPodYNPpq6xlQnlsN6A//MaNQi795Ot+FNOiuqqTA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-27T23:35:35Z"
  mac: ENC[AES256_GCM,data:cFsMI0QyaVzb9R5uIn8hqQJLJ/g8iUSKcPD5mlKEpkoxXwExSg2/07mkvAJ9I6xDYI+nJb1uGN1PcqbXKmmoCQzH7Z+NKBPCOuO2X/YzPutaEwwJiNVZwAnUhdTHb8k4kZdZyGo6Gogw5VJjhIBE5/F+kIxE+KoLBQapg0QGNhM=,iv:7ZQq+eRncb2H9uQZgk64yvpteqX94Qax1hxUju4lFvw=,tag:NOoel4DCfE1vAUCIOh+RmA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
