apiVersion: v1
kind: Secret
metadata:
  name: authentik-terraform-secrets
type: Opaque
stringData:
  authentik_token: ENC[AES256_GCM,data:QWxH+8uDIM96GdEzRE6VhmZsto4ENdYOw56N7VF+IGVMgLD4PGQGXQjnz18CGt7co6yN/63AXXnu3UBU,iv:MmaVytwFlhguNZaUFFxonEJWwbO5D3QSKSLbH60zmVI=,tag:8AI6BdH0dZit5DDE3s6kPQ==,type:str]
  access_token_validity: ENC[AES256_GCM,data:9dqyebu2Wik=,iv:ZRIdn5H6yqTw1oPdlvUWNfzbHT4LOQZd82WIS3eU5eI=,tag:HNZbM8qjeieA3t64Lg7YWw==,type:str]
  refresh_token_validity: ENC[AES256_GCM,data:9wcXwtOoeQ==,iv:3DhcTg/x0bq6XwN4t/Xstlmmrwyy03yKqcJREq8v3Gg=,tag:6achQijsv4eiHD1cD2WeyA==,type:str]
  ldapservice_password: ENC[AES256_GCM,data:j7sbMJWKAe3wLNz99l+KznJO339/AL6f78zMqOFT2BM=,iv:PX1L//mc0oQiCFamgVMkc9auFB9Pxo7qOulszHWQ+C4=,tag:HK+zCcSFbturwG0iPVDzPg==,type:str]
sops:
  age:
    - recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwZ1ZxMlRvZW83Tzh1QlEy
        Z01PeWlWanRwMzVrRWhpdXZ4Z3ppNlZwSnprCmxSc2tyL29TZTBDSjhTR1kzZ0Zv
        U1hNSkI1YjlXR2R3RXVQMDgvSGtiN1UKLS0tIDdLSzc5WSs3c2hieDNlSGJSQmFC
        a1JoaXZONUFrRVMzNy93Vk1lUEIwZVEKpctjQxtv5VbPg1648iN/8/5QxQi98usB
        8LBcLsyhMXiCOiWljtQIFRUyBkhBkAU4jPcL0IZfooAfA43JpRUqmA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-01T02:42:48Z"
  mac: ENC[AES256_GCM,data:vzkBPJZXNPGeZ2iKvDIMoryZVKz1X7Uyz8N2617Pwb1NFercJIctq1Lb6SdFKSTj39cqkuH8ecZFauTXMbbeIyhZX4M5Xs1zAcr960HL9P4coGDvAnE2bYA4SGOA3i6WAZpqoE96NDHntYYS0+TDlYgqEn35SFix9drzJ8Y9dWs=,iv:aQX/Y8hjFocyGoQ+rEOc0vcTz0DPZM+/31242AxDmTM=,tag:qYg3T6ArGmXiX3AVWqq3Lw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
