apiVersion: v1
kind: Secret
metadata:
  name: authentik-terraform-secrets
type: Opaque
stringData:
  authentik_token: ENC[AES256_GCM,data:KByu3STAW2djssQ68MzDbWEM+p0ea9oscENqqhpAf/3yxs2/PObaM4QzePVNMOma+vSPuXJpjevNgtge,iv:ngucv/BABT4v9oUFXMrihF1DCdDjGgPASlq86Xxh/nA=,tag:IdUDa2wcwZNN9mlyW21MvA==,type:str]
sops:
  age:
    - recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqNjhKUjFXbXp0Y3gwR1hq
        eUg1a3BTUkdjN25BTHNoSk95QW5mWU9qclYwCmNPeHpIZHFlMGpraGE4TkJUTTZn
        SFVPR2M5ckRyNmUzRmR3NGxqNjNMN2cKLS0tIEtDRU9LMG9KcTlhQlZwakYyS0R0
        WVVHUkl4OWJubVA5NkhQRUtFVEg5NGMKJcJ97m8mLVKhO+uBk6Pn51T6qOMC9Hh5
        oOdH2WHQsfmWdBtDvZYdb2Rw7SboKrxvGzXy/0f0zLH06HTm2OXlrw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-12T05:59:21Z"
  mac: ENC[AES256_GCM,data:+hynUyRMiqHCRSHNWHHKbemXZ6YYYgFYOIO1fINnZ9sTJ2u2efnCSGQBUlO2Jm1hwfo3+nPCdeY2d5jPHhSvAbF1CbgkWY4AdNXTxaf3m8B8nzW8YlpIYhTlgPJf5e1rWQB3o2z6NOG+5XI/CvdvxQLLmJIfz62PSkR1hlFwKVQ=,iv:mukAZ38GaIjSXXirGltlcizu5NQSfUzS7my/jCPhvbY=,tag:otGlbLt6yX/jGqg6FNtRCQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
