apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  aws-access-key-id: ENC[AES256_GCM,data:bAqFzthEocg/lWCVkoOBGTMDJq8=,iv:NLFYpVewOHwWwW4jhrSrn1P2X5bekBbaD3hMR+wMk7U=,tag:QPfIvQSgM0mKZAB4fFNjOg==,type:str]
  aws-secret-access-key: ENC[AES256_GCM,data:Q5Y5JwXrz/Mwo1gbQduyBJVjzKtfwPGkeVybKbpCTYDDMJygYiCUSQ==,iv:CP2WEdcKvkPAueYMeHs1RjzvuI3xhHgwt/GW7FwNHv4=,tag:fikwAwJd1IR/fq3rqjh7KQ==,type:str]
sops:
  age:
    - recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4YjFuSCtxNENhODVHQVZR
        YlI4ZFNManpOdlVJSGNXNjRBYkhLdVBuNUZvCnJkNFl5OXVzMG84ZnZUTERIS1F1
        MDY0QWRTd0JHSW9Kd2plWVJwYXVOMjgKLS0tIHRtQVFVakh0WGhaR01POTRjRWhI
        MHd6OUl2ZTVKM1FZRkZkRGpZTVJxRXMK5Q/sSWxgCZQ5TX+BwuWojX/ZOTr9fjQX
        QDXKAkRTQOHBaxveB3ASGjbbpRMP43+m2Bre3mIi66tocQVYlsGZuQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-12T04:43:07Z"
  mac: ENC[AES256_GCM,data:EKpfRMfUorH5l91U8xiMlhTJy0/7+9kXlvE3flNVYd2UZwq1ASTR9Ad3jb8e1wy19czs4wY8M0NcCowsMj1lSV/nhEUDyD/r17iSTgge4uuhCrN27Q4tdvWXtKePDPg68nr1+MlpyGX5iEIdKwO5biuQyclfbxp053xgmEW2H+s=,iv:XabHRjWqcMcOyg+80XJdzGje7Cb7+o2rlHX5sEAEPz0=,tag:U3k+6u06gG7Dxq02Wzn70Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
