apiVersion: v1
kind: Secret
metadata:
  name: firefly-secrets
type: Opaque
stringData:
  APP_KEY: ENC[AES256_GCM,data:V9EdJnP4OGea3B+Cn5IAzFv9vvG6QGAlU6N7W26f4RM=,iv:VIow5uFpAoBfQWkucHAuaB1WS3VoUQY60dvUeWXGGoA=,tag:IlDP/keFVAqGU1IMLxhJeg==,type:str]
  SITE_OWNER: ENC[AES256_GCM,data:sv2E1XIeLII6FhJxMi3Zyk/eaHA9tWz6,iv:BiZE/TIRplEj8ZMCxOfmkUYvRyRkRJacIdCJ2FxSg58=,tag:HcRTKMrk7TZIbEX1ntmQLg==,type:str]
  DB_HOST: ENC[AES256_GCM,data:3kGh9/fqTaUdI81hbsBzWHz64E+fKTn0RLVw1+TjogE8eJdDpmE=,iv:ODl5xYGTLr8M8kh4AYT0CGkDKU9TscQR2TIuAkAqkN4=,tag:okLnItOhLyWQrL8rqOSdCw==,type:str]
  DB_PORT: ENC[AES256_GCM,data:aWJLqA==,iv:fy/c8wk+KT1x0GOO2UnLPaHYEdDGTa3ZtCMiBlhgDLQ=,tag:WztdrcPYZBm2nGm4tzOJgw==,type:str]
  DB_CONNECTION: ENC[AES256_GCM,data:ht/ypoU=,iv:3Z6QUz2c7eZnPOKUWE+TPtFLGDZb2IbGs1vJkJ5NZoM=,tag:755qJeVj3A4ZDR4l83DpWg==,type:str]
  DB_DATABASE: ENC[AES256_GCM,data:B/aAhow8ug==,iv:w0E9AdkDrBis6hvYAaulDLX8CICEYqQnM9h76rNzzm4=,tag:ikp6xfuwF0nh+0EvpWHHWA==,type:str]
  DB_USERNAME: ENC[AES256_GCM,data:i7QT7yHvAA==,iv:XGYuzavbStOo9+z9xXc3pcI8vqiPfS07o2ovmVZYOGs=,tag:xagLuQYnEG4zoWVB3mns3w==,type:str]
  DB_PASSWORD: ENC[AES256_GCM,data:QLkXbpvB50WibgLu3XKomR/haDOCnKyXOtnWM8o7wH6WByne6a234MJ+SeFkZxDy,iv:LkaRWu7anszipqXtIYE28EhwalgdN3zvPMFshbPJuwA=,tag:jazL41MN5S+VovfVMIiSXQ==,type:str]
  PGSQL_SSL_MODE: ENC[AES256_GCM,data:ArF3twc1,iv:LFLfOfVBmdp5aW4f9iLt8l2+eFLusjG4L3aSx61v0Ag=,tag:UfKbeGLIsRbw897YlWlkDA==,type:str]
  PGSQL_SCHEMA: ENC[AES256_GCM,data:VrtkHWGZ,iv:zeeMYbwspyn1pw0qnn1C89QqKLJSLfTUb4F4he2M2xc=,tag:Zc99yz5ALLqOR+JYOU45tw==,type:str]
  MAIL_MAILER: ENC[AES256_GCM,data:zqB8,iv:D1UlWn0QKi0kQwQX2kVWQZQFpi17LUtAOapl4gcBxiQ=,tag:TTMSSCzc/TsnNGskVs7tzA==,type:str]
  MAIL_HOST: ENC[AES256_GCM,data:fmtepcef0rmKqhUbSvLl1Z45,iv:h/BE3oCyhgg9lPM2Z1+maUbIgSWP07pqrJdupdpW3B4=,tag:2VrgLo4pghlACrRBBr0eng==,type:str]
  MAIL_PORT: ENC[AES256_GCM,data:2t+d,iv:fIN4MZs/PDYby7KM756DIeQA8+yIOVb/KhcCwzuw+ZM=,tag:Bvb3+bCDWi4w78sUi49BKA==,type:str]
  MAIL_FROM: ENC[AES256_GCM,data:7cCgZJ2m9xJ1wnqL5rSWtdQ6KahCOqEXSQ==,iv:Q3CJP2nCmnrYWJwu+JyW8VP+Rs+sLkjtiEz2TKSqLhg=,tag:MQ+cRZKFhRikh4Hd5+RHpw==,type:str]
  MAIL_USERNAME: ENC[AES256_GCM,data:clCwqPTJq6qk/MzP8hJ0L72Qs014YHFBoQ==,iv:ulI0P5Kru/CZ4nmLd2Tz29i/m5qYwy2MAB0vcU3d7wE=,tag:5HhP2Fj3R0GSNsgNwm5vLA==,type:str]
  MAIL_PASSWORD: ENC[AES256_GCM,data:wbeGmR6la334iptup4n53g==,iv:6Gv3DaUT2vFLgimSX6eGeADnpIdV6CBGf92YMOQnpVg=,tag:60itVKtiaUdN9GCFjVsY4A==,type:str]
  MAIL_ENCRYPTION: ENC[AES256_GCM,data:TQrW,iv:Eb7e8ycUsPW2ltEDZPRtRd0YKxwcssv4GqUnxH4klQI=,tag:QrAkTIBx7OJu3x1734wDBQ==,type:str]
  MAP_DEFAULT_LAT: ENC[AES256_GCM,data:e6Ejw6TRhyk=,iv:zhrCCvE9ZJlgAv3Z3fWreeI961S1dCBq5z5DJju/fjE=,tag:Ki5/iVmq25cuBCz3d/dvxw==,type:str]
  MAP_DEFAULT_LONG: ENC[AES256_GCM,data:zCPU82vQ8VCxdg==,iv:8GBNdpBawW6DCxZwbYK/tBOOVOTW1D9BJ5EnFrIvDxQ=,tag:DURDt1UtvJ/WZ2TfAxqYpg==,type:str]
  MAP_DEFAULT_ZOOM: ENC[AES256_GCM,data:ig==,iv:J2lZe8y1iPq8Erz+ji9wgV324qeI5U0pQvRa2LtHFBo=,tag:t7LBBupKf1h1CNlPy3wzLA==,type:str]
  STATIC_CRON_TOKEN: ENC[AES256_GCM,data:0oEWrs9beOFmBwlDdmHaQU1PNciYWo0jbq4a58r231Q=,iv:qXWkXtCG1ZFl5d7UjZ1xczvD/P6XpC/PMjnfRUlthbU=,tag:Psw1N2BNHCkXVHIzXZbYNg==,type:str]
sops:
  age:
    - recipient: age185l4m6q0d4dxv4kd6slhlqgl88fyz3xlx8xkv76tyfr4chvw6eys96xsu9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZSzIzUTRYSjNidGhmaXY1
        NWFzOE5Ca0phZ1Z1YW13Y1VrZHBnVFk5ekVzCmhMQ2FSZXFlN3Jpc0M4MXV4MDcv
        ZEdia1ViR2hXQW0rbUNyeSt3TlUrbjAKLS0tIFZzVWhOaXF1VFFWT2dMZCt3S0ZQ
        c3BTdjdtdzdFVWJ6K2ZnOExFQ040LzgK1Klq1j4EyhGWUenBgtoxYbDFp9lo77N7
        Wb8auW4FWPQU+UIZsfflOLT4zFvknVjfQyXCfMxp+QVoRkN5csJ9yg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-26T18:04:32Z"
  mac: ENC[AES256_GCM,data:65fDixG66W/aDZ7KxuPqqe5XZPL7TCZ5/yxZ6DvVJiA7Rvyx1HupY709iPm0Q+cK8oPuqKOPQ+SYng90nQ2Pc8Zo/wFgSQ2j/totHunVny8JAh2tDG7uZCcdeG/L9AnY78aX8LmEdRDGvW5EdfWYPIjwMTU/pgd3NyIgXsom0w0=,iv:AptgykYkCKenKMtZR2MkaFN0Nox2YJb8LplmHW90NkM=,tag:0T8jY0+1CmbxMbQqqmovqw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
