---
apiVersion: v1
kind: Namespace
metadata:
  name: network
  labels:
    ns: network
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: baseline
    pod-security.kubernetes.io/warn: baseline
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
