---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: budget

components:
  - ../../components/sops

resources:
  - ./namespace.yaml
  # - ./wallos/ks.yaml
  # - ./firefly/ks.yaml
  # - ./firefly-importer/ks.yaml
